Repository easybuilders/easybuild-easyblocks, pull requests merged in 2018-03, with the labels that each got.

#1372 temporarily disable test suite runs for environment modules
  .travis.yml
Labels: change

#1370 bump version to 3.5.2 & update release notes
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1373 release EasyBuild v3.5.2
  .travis.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/c/comsol.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/perlmodule.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/i/icc.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/o/octave.py
  easybuild/easyblocks/s/stata.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/tkinter.py
Labels: update

#1375 sync with master + bump to 3.6.0dev
  .travis.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1374 Make gromacs easyblock select build type from toolchainopt debug setting.
  easybuild/easyblocks/g/gromacs.py
Labels: enhancement

#1376 re-enable testing against environment modules, bump Lmod to 7.7.16
  .travis.yml
  test/easyblocks/module.py
Labels: change

#1378 enhance Gurobi easyblock to support installing Python bindings
  easybuild/easyblocks/g/gurobi.py
Labels: enhancement

#1380 bump version to 3.5.3 & update release notes
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1381 release EasyBuild v3.5.3
  .travis.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/g/gurobi.py
  test/easyblocks/module.py
Labels: update

#1382 sync with master after EasyBuild v3.5.3 release
  RELEASE_NOTES
Labels: update

#1384 add support to PythonPackage easyblock to install with 'pip install --editable'
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#1383 enhance RPackage easyblock to support installing from unpacked sources
  easybuild/easyblocks/generic/rpackage.py
Labels: enhancement

#1385 Added $EBROOTIFORT/include in CPATH
  easybuild/easyblocks/i/ifort.py
Labels: enhancement

#1387 fix linking to FFTW for Doris: should be -lfftw3f
  easybuild/easyblocks/d/doris.py
Labels: bug fix

#1389 add additional location to $PATH for FLUENT installations
  easybuild/easyblocks/f/fluent.py
Labels: enhancement

#1388 add houndci + flake8 configuration
  .flake8.ini
  .hound.yml
Labels: enhancement

#1386 TensorFlow 1.6.0 fix: use the absolute path for the C compiler when compiling with GPU support
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1391 make PythonPackage generic easyblock aware of 'unpack_options' easyconfig parameter
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#1394 minor updates to ABAQUS easyblock to support latest version
  easybuild/easyblocks/a/abaqus.py
Labels: update
