Repository easybuilders/easybuild-easyblocks, pull requests merged in 2018-12, with the labels that each got.

#1597 Enable TensorFlow to detect any MPI runtime supported in EB
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#1596 Fix Gromacs use of MKL for non-Intel compilers (e.g. gomkl toolchain).
  easybuild/easyblocks/g/gromacs.py
Labels: bug fix

#1598 enhance Bundle easyblock to allow installation of bundle components with additional easyblocks + build components in parallel
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix, enhancement

#1313 Add support for OTF in tau.py.
  easybuild/easyblocks/t/tau.py
Labels: enhancement

#1309 Re-add missing VT_(S)LIB_DIR env variable to itac module.
  easybuild/easyblocks/i/itac.py
Labels: bug fix

#1575 modified vmd.py so that configopts don't contain duplicate values (otherwise it fails to rebuild)
  easybuild/easyblocks/v/vmd.py
Labels: bug fix

#1585 Added the openmp flags in the linker flags in mumps.py
  easybuild/easyblocks/m/mumps.py
Labels: bug fix

#1579 update trinity easyblock for latest version 2.8
  easybuild/easyblocks/t/trinity.py
Labels: enhancement

#1604 inform Hound about Python 2 builtins
  setup.cfg
Labels: bug fix

#1311 Pre v3 of OpenFOAM needs extra flag to build with newer g++
  easybuild/easyblocks/o/openfoam.py
Labels: enhancement

#1601 Trilinos - Support build against MKL
  easybuild/easyblocks/t/trilinos.py
Labels: enhancement

#1600 add custom easyblock for RepeatMasker
  easybuild/easyblocks/r/repeatmasker.py
Labels: new

#1605 update release notes + bump version for EasyBuild v3.8.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1606 release EasyBuild v3.8.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/c/cp2k.py
  easybuild/easyblocks/f/fdtd_solutions.py
  easybuild/easyblocks/f/fftw.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/mesonninja.py
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/generic/scons.py
  easybuild/easyblocks/i/icc.py
  easybuild/easyblocks/i/ifort.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/i/itac.py
  easybuild/easyblocks/m/mothur.py
  easybuild/easyblocks/m/mumps.py
  easybuild/easyblocks/m/mvapich2.py
  easybuild/easyblocks/n/netcdf4_python.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/p/pgi.py
  easybuild/easyblocks/p/psi.py
  easybuild/easyblocks/q/quantumespresso.py
  easybuild/easyblocks/r/repeatmasker.py
  easybuild/easyblocks/s/scotch.py
  easybuild/easyblocks/s/siesta.py
  easybuild/easyblocks/t/tau.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/trilinos.py
  easybuild/easyblocks/t/trinity.py
  easybuild/easyblocks/v/vmd.py
  easybuild/easyblocks/w/wps.py
  easybuild/easyblocks/w/wrf.py
  setup.cfg
  test/easyblocks/module.py
Labels: update

#1607 sync with master + update version to 3.8.1dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update
