Repository easybuilders/easybuild-easyblocks, pull requests merged in 2018-05, with the labels that each got.

#1415 add conditional so "--with-x" is only added to configopts if not defined
  easybuild/easyblocks/r/r.py
Labels: bug fix

#1414 update Maple easyblock to support recent versions
  easybuild/easyblocks/m/maple.py
Labels: update

#1419 Enabled nc-config usage for netCDF in ESMF >=7.1
  easybuild/easyblocks/e/esmf.py
Labels: enhancement

#1422 fixed ICEM_ACN path
  easybuild/easyblocks/a/ansys.py
Labels: bug fix

#1421 enhance PETSc easyblock for version 3.9
  easybuild/easyblocks/p/petsc.py
Labels: enhancement

#1377 add support for detecting auto-downloaded dependencies in PythonPackage easyblock
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#1413 Install Chimera in a subdirectory to avoid its dependencies being added to the environment
  easybuild/easyblocks/c/chimera.py
Labels: bug fix

#1427 assume PGI Community edition is used when no license file is specified
  easybuild/easyblocks/p/pgi.py
Labels: change

#1426 support adding specific paths to $PATH for generic Binary easyblock via 'prepend_to_path' custom easyconfig parameter
  easybuild/easyblocks/generic/binary.py
Labels: enhancement

#1397 add support to enable integration of pscom in psmpi easyblock
  easybuild/easyblocks/p/psmpi.py
Labels: enhancement

#1428 avoid hardcoding defaults in question patterns in Doris easyblock
  easybuild/easyblocks/d/doris.py
Labels: bug fix

#1420 Make configure and make look for FoX in EBROOTFOX in QuantumESPRESSO easyblock
  easybuild/easyblocks/q/quantumespresso.py
Labels: bug fix

#1424 fix suffix for Boost Python library in Boost 1.67.0 & newer
  easybuild/easyblocks/b/boost.py
Labels: update

#1392 imkl: fix sanity check overwriting base libs with interface libs.
  easybuild/easyblocks/i/imkl.py
Labels: bug fix

#1429 bump version to 3.6.1 & update release notes
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1432 release EasyBuild v3.6.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/ansys.py
  easybuild/easyblocks/b/boost.py
  easybuild/easyblocks/c/chimera.py
  easybuild/easyblocks/d/doris.py
  easybuild/easyblocks/e/esmf.py
  easybuild/easyblocks/generic/binary.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/i/imkl.py
  easybuild/easyblocks/m/maple.py
  easybuild/easyblocks/m/matlab.py
  easybuild/easyblocks/p/petsc.py
  easybuild/easyblocks/p/pgi.py
  easybuild/easyblocks/p/psmpi.py
  easybuild/easyblocks/q/quantumespresso.py
  easybuild/easyblocks/r/r.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/w/wien2k.py
Labels: update

#1433 sync with master & bump version to 3.6.2dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1430 move flake8 configuration to setup.cfg and make HoundCI aware of it
  .flake8.ini
  .hound.yml
  setup.cfg
Labels: code cleanup
