Repository easybuilders/easybuild-easyblocks, pull requests merged in 2018-11, with the labels that each got.

#1307 Make FDTD_Solutions easyblock do the install with copytree instead of rpm rebuild
  easybuild/easyblocks/f/fdtd_solutions.py
Labels: bug fix

#1563 ENH: update WRF and WPS to support version 4
  easybuild/easyblocks/w/wps.py
  easybuild/easyblocks/w/wrf.py
Labels: update

#1572 Fix TensorFlow test tempdir problem
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1577 enhance sanity check for icc & ifort: also check for compilers_and_libraries_*/linux subdirectory
  easybuild/easyblocks/i/icc.py
  easybuild/easyblocks/i/ifort.py
Labels: enhancement

#1578 fix running netcdf4-python tests to also support installation as extension
  easybuild/easyblocks/n/netcdf4_python.py
Labels: bug fix

#1576 enhance Mothur easyblock to support use of Boost and HDF5 as dependencies
  easybuild/easyblocks/m/mothur.py
Labels: enhancement

#1580 add version check in sanity check step of SCOTCH easyblock (+ code cleanup)
  easybuild/easyblocks/s/scotch.py
Labels: code cleanup, enhancement

#1568 adapt PSI easyblock for PSI4 > 1.2
  easybuild/easyblocks/p/psi.py
Labels: update

#1584 add support in Clang easyblock to skip running of all tests
  easybuild/easyblocks/c/clang.py
Labels: enhancement

#1546 add support for impi version 2019
  easybuild/easyblocks/i/impi.py
Labels: update

#1591 fix location of path-to-source argument in configure command of CMakeMake
  easybuild/easyblocks/generic/cmakemake.py
Labels: bug fix

#1594 avoid hardcoding 'PREFIX=<installdir>' in build/install options when using SCons easyblock
  easybuild/easyblocks/generic/scons.py
Labels: enhancement

#1586 avoid hardcoding --with-rdma configure option in MVAPICH2 easyblock
  easybuild/easyblocks/m/mvapich2.py
Labels: bug fix
