Repository easybuilders/easybuild-easyblocks, pull requests merged in 2018-09, with the labels that each got.

#1496 customise check_checksums method in Bundle easyblock
  easybuild/easyblocks/generic/bundle.py
Labels: enhancement

#1495 don't set $BOOST_ROOT when only installing Boost Python bindings
  easybuild/easyblocks/b/boost.py
Labels: bug fix

#1494 IMPROVE PGI siterc so it allows -pthread switch
  easybuild/easyblocks/p/pgi.py
Labels: enhancement

#1505 bump Lmod version used in Travis config to 6.6.3 (now required by framework)
  .travis.yml
Labels: change

#1503 add generic ModulesRC easyblock
  easybuild/easyblocks/generic/modulerc.py
  test/easyblocks/module.py
Labels: new

#1504 Add a pkgconfig file to HDF5 when installing.
  easybuild/easyblocks/h/hdf5.py
Labels: enhancement

#1486 use short build dir for Trilinos + link with libmetis.a (REVIEW)
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/t/trilinos.py
Labels: bug fix

#1509 make IntelBase generic easyblock aware of (pre)installopts
  easybuild/easyblocks/generic/intelbase.py
Labels: enhancement

#1512 add custom easyblock for VEP
  easybuild/easyblocks/v/vep.py
Labels: new

#1513 take (pre)installopts into account in RPackage generic easyblock
  easybuild/easyblocks/generic/rpackage.py
Labels: enhancement

#1507 Add support for IntelMPI in TensorFlow.
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#1514 don't check for mcc in MATLAB sanity check as it requires a specific toolbox license
  easybuild/easyblocks/m/matlab.py
Labels: change

#1489 added regex to fix WM_PROJECT_VERSION correctly
  easybuild/easyblocks/o/openfoam.py
Labels: enhancement

#1518 back up existing .modulerc file + print informative message in ModuleRC easyblock
  easybuild/easyblocks/generic/modulerc.py
Labels: bug fix

#1519 Make sure bazel doesn't write files in $HOME/.cache when building tensorflow
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1498 FSL - Improve configuration choice
  easybuild/easyblocks/f/fsl.py
Labels: bug fix

#1510 update Siesta easyblock for v3.2 to 4.1-b3
  easybuild/easyblocks/s/siesta.py
Labels: bug fix, enhancement

#1520 Enabling VSX on POWER for FFTW >= 3.3.7.
  easybuild/easyblocks/f/fftw.py
Labels: bug fix

#1506 sidestep using the config.guess that comes with a package in ConfigureMake generic easyblock
  easybuild/easyblocks/generic/configuremake.py
  test/easyblocks/general.py
Labels: enhancement

#1522 only read 'configure' script when it's actually there
  easybuild/easyblocks/generic/configuremake.py
Labels: bug fix

#1523 fix typo in ConfigureMake easyblock
  easybuild/easyblocks/generic/configuremake.py
Labels: bug fix

#1524 move finding of config.guess in ConfigureMake easyblock into configure_step
  easybuild/easyblocks/generic/configuremake.py
Labels: bug fix

#1521 update DOLFIN easyblock for latest version (2018.1)
  easybuild/easyblocks/d/dolfin.py
Labels: update

#1525 Trilinos: Add librt as dependency when linking suitesparse.
  easybuild/easyblocks/t/trilinos.py
Labels: bug fix

#1526 bump version to 3.7.0 & update release notes
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1527 release EasyBuild v3.7.0
  .travis.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/amber.py
  easybuild/easyblocks/a/ansys.py
  easybuild/easyblocks/b/boost.py
  easybuild/easyblocks/b/bwise.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/d/dolfin.py
  easybuild/easyblocks/e/eigen.py
  easybuild/easyblocks/f/fftw.py
  easybuild/easyblocks/f/fsl.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/configuremake.py
  easybuild/easyblocks/generic/intelbase.py
  easybuild/easyblocks/generic/modulerc.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/generic/rpackage.py
  easybuild/easyblocks/generic/scons.py
  easybuild/easyblocks/h/hdf5.py
  easybuild/easyblocks/i/ipp.py
  easybuild/easyblocks/m/matlab.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/p/pgi.py
  easybuild/easyblocks/q/quantumespresso.py
  easybuild/easyblocks/s/scalapack.py
  easybuild/easyblocks/s/siesta.py
  easybuild/easyblocks/s/superlu.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/trilinos.py
  easybuild/easyblocks/v/vep.py
  easybuild/easyblocks/w/wien2k.py
  test/easyblocks/general.py
  test/easyblocks/module.py
Labels: update

#1528 sync with master + bump to 3.7.1dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/t/trilinos.py
Labels: update

#1531 support bypassing use of system type obtained with recent config.guess in ConfigureMake
  easybuild/easyblocks/generic/configuremake.py
Labels: code cleanup, enhancement

#1530 fix checking for downloaded dependencies for stand-alone installations in PythonPackage generic easyblock
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#1532 also specify --host option to configure script based on config.guess result in ConfigureMake easyblock
  easybuild/easyblocks/generic/configuremake.py
Labels: bug fix, enhancement
