Repository easybuilders/easybuild-easyblocks, pull requests merged in 2019-07, with the labels that each got.

#1762 extend question patterns with 'https' URL entry in Modeller easyblock for recent verisons
  easybuild/easyblocks/m/modeller.py
Labels: update

#1754 also add --without-go configure option for SWIG as we ''disable everything by default"
  easybuild/easyblocks/s/swig.py
Labels: bug fix

#1756 GCC: Allow bootstrapping with profile-guided optimizations
  easybuild/easyblocks/g/gcc.py
Labels: enhancement

#1763 Healpix.py: modextrapaths implemented on easyblock level, sanity_check_step, gcc_target added
  easybuild/easyblocks/h/healpix.py
Labels: enhancement

#1765 update OpenBLAS easyblock to be aware of POWER9 support in OpenBLAS 0.3.6
  easybuild/easyblocks/o/openblas.py
Labels: update

#1764 Using dict-type checksums for CUDA, with custom source filename
  easybuild/easyblocks/c/cuda.py
Labels: enhancement

#1750 don't assume cmake arguments when configure_cmd is set in CMakeMake easyblock
  easybuild/easyblocks/generic/cmakemake.py
Labels: bug fix

#1745 Rosetta block: also install docs and demos
  easybuild/easyblocks/r/rosetta.py
Labels: enhancement

#1767 update release notes + bump version for EasyBuild v3.9.3
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1768 release EasyBuild v3.9.3
  .travis.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/e/easybuildmeta.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/h/healpix.py
  easybuild/easyblocks/h/hpcg.py
  easybuild/easyblocks/m/modeller.py
  easybuild/easyblocks/o/openblas.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/r/rosetta.py
  easybuild/easyblocks/s/snphylo.py
  easybuild/easyblocks/s/swig.py
Labels: update

#1769 sync with master + bump version to 3.9.4dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1770 Add easyblock for MSM
  easybuild/easyblocks/m/msm.py
Labels: new

#1766 Using dict-type checksums for CUDA, with custom source filename
  easybuild/easyblocks/c/cuda.py
Labels: enhancement

#1758 update WIEN2k easyblock to support version 19.1 (REVIEW)
  easybuild/easyblocks/w/wien2k.py
Labels: update

#1771 only check for qtwebengine if glibc is sufficiently recent
  easybuild/easyblocks/q/qt.py
Labels: bug fix

#1749 Workaround for XCrySDen for Tcl 8.6
  easybuild/easyblocks/x/xcrysden.py
Labels: enhancement

#1712 MATLAB: allow specifying the license file directly
  easybuild/easyblocks/m/matlab.py
Labels: enhancement
