Repository easybuilders/easybuild-easyblocks, pull requests merged in 2019-01, with the labels that each got.

#1611 run 'make check' in parallel for GROMACS since it involves more compilation
  easybuild/easyblocks/g/gromacs.py
Labels: enhancement

#1612 avoid that (system) Intel compilers are always considered when building SuiteSparse
  easybuild/easyblocks/s/suitesparse.py
Labels: bug fix

#1614 fix missing import statement in ROOT easyblock
  easybuild/easyblocks/r/root.py
Labels: bug fix

#1610 Handle multiple installation keys for MATLAB
  easybuild/easyblocks/m/matlab.py
Labels: enhancement

#1603 cleanup in Perl and PerlModule easyblocks
  easybuild/easyblocks/generic/perlmodule.py
  easybuild/easyblocks/p/perl.py
Labels: code cleanup

#1617 Mathematica: let's answer SELinux question with 'no'?
  easybuild/easyblocks/m/mathematica.py
Labels: bug fix

#1545 Fixed incorrect LibInt reference, and added support for CP2K 6.1
  easybuild/easyblocks/c/cp2k.py
Labels: bug fix, update

#1582 check current start_dir value before appending 'src' subdirectory in MrBayes easyblock
  easybuild/easyblocks/m/mrbayes.py
Labels: bug fix

#1619 enhance Python easyblock to also include <prefix>/include/python* in $CPATH
  easybuild/easyblocks/p/python.py
Labels: enhancement

#1609 Make openfoam easyblock handle debug build.
  easybuild/easyblocks/o/openfoam.py
Labels: enhancement

#1620 revert change that adds 'include/python<version>*' to $CPATH for Python
  easybuild/easyblocks/p/python.py
Labels: bug fix

#1623 disable 'build isolation' feature in pip > 10.x
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#1455 define $LDSHARED when installing Python packages when Python's value doesn't use toolchain compiler ($CC)
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#1624 update release notes + bump version for EasyBuild v3.8.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1626 bump version to 3.9.0dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update
