Repository easybuilders/easybuild-easyblocks, pull requests merged in 2019-10, with the labels that each got.

#1815 update RepeatMasker easyblock for version 4.0.9
  easybuild/easyblocks/r/repeatmasker.py
Labels: update

#1823 update TensorFlow easyblock to support TensorFlow 2.0
  easybuild/easyblocks/t/tensorflow.py
Labels: update

#1824 add support in TensorFlow easyblock to run a custom test script as smoke test
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#1825 add support for installing QScintilla on top of PyQt5
  easybuild/easyblocks/q/qscintilla.py
  test/easyblocks/module.py
Labels: update

#1826 make sure "generic=True" actually turns on generic build in GCC easyblock
  easybuild/easyblocks/g/gcc.py
Labels: bug fix

#1819 Add easyblock for installing MotionCor2.
  easybuild/easyblocks/m/motioncor2.py
  test/easyblocks/module.py
Labels: new

#1822 add --verbose flag to 'pip install' when running EB in debug mode
  easybuild/easyblocks/generic/pythonpackage.py
Labels: change, enhancement

#1772 openfoam v1906 reorganized their wmake rules and now rely on General/…
  easybuild/easyblocks/o/openfoam.py
Labels: update

#1827 Make an easyblock for Gctf in the same style as MotionCor2.
  easybuild/easyblocks/g/gctf.py
  test/easyblocks/module.py
Labels: new

#1829 add CMakeNinja easyblock, which is needed for building Qt5Webkit.
  easybuild/easyblocks/generic/cmakeninja.py
Labels: new

#1828 update VEP easyblock to make installation compatible with Bio::EnsEMBL::XS
  easybuild/easyblocks/v/vep.py
Labels: enhancement

#1831 fix compatibility of Trilinos easyblock with Python 3
  easybuild/easyblocks/t/trilinos.py
Labels: bug fix

#1832 update release notes and bump version for v4.0.1 release
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1833 release EasyBuild v4.0.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/b/boost.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/g/gctf.py
  easybuild/easyblocks/generic/cmakeninja.py
  easybuild/easyblocks/generic/configuremake.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/l/libxml2.py
  easybuild/easyblocks/m/motioncor2.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/q/qscintilla.py
  easybuild/easyblocks/r/repeatmasker.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/trilinos.py
  easybuild/easyblocks/v/vep.py
  test/easyblocks/module.py
Labels: update

#1834 sync develop with master and bump version to 4.0.2dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1835 cuda.py: Handle cuda-installer.log
  easybuild/easyblocks/c/cuda.py
Labels: bug fix
