Repository easybuilders/easybuild-easyblocks, pull requests merged in 2019-04, with the labels that each got.

#1671 always set self.pylibdir in PythonPackage.set_pylibdirs(), which is important when installing Python packages for multiple Python versions via multi_deps
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#1618 make sure CMake doesn't pick up on system Boost in CMakeMake generic easyblock (
  easybuild/easyblocks/generic/cmakemake.py
Labels: enhancement

#1675 fix custom definition of load_module method in LAPACK module
  easybuild/easyblocks/l/lapack.py
Labels: bug fix

#1673 Make sure meson has -Dlibdir=lib so it doesn't install libraries in lib/x86_64-linux-gnu on Debian/Ubuntu multiarch systems
  easybuild/easyblocks/generic/mesonninja.py
Labels: enhancement

#1668 replace -openmp with -fopenmp when building TINKER with Intel compilers (+ modernize easyblock)
  easybuild/easyblocks/t/tinker.py
Labels: code cleanup, enhancement

#1677 pass down compiler names and options to Qt5 5.8 & more recent via corresponding QMAKE_* configuration options
  easybuild/easyblocks/q/qt.py
Labels: bug fix, enhancement

#1678 also take into account 'custom_paths' passed down to sanity_check_step before injecting default sanity_check_paths value that uses %(pyshortver)s template value
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#1681 update release notes for EasyBuild v3.9.0 release + bump version to 3.9.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1685 sync with master & bump version to 3.9.1dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1679 Update CGAL easyblock to support CGAL 4.12 & newer
  easybuild/easyblocks/c/cgal.py
Labels: enhancement

#1687 use temporary directory for pip cache (rather than $HOME/.cache/pip)
  easybuild/easyblocks/generic/pythonpackage.py
Labels: change

#1688 allow oversubscription when testing FFTW on top of OpenMPI >= 3.0
  easybuild/easyblocks/f/fftw.py
Labels: enhancement

#1666 only install mkl-dnn by default with TensorFlow on x86-64 systems
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#1690 fix import statement for DUMMY_TOOLCHAIN_NAME
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/generic/buildenv.py
  easybuild/easyblocks/generic/systemmpi.py
  easybuild/easyblocks/l/libxml2.py
  easybuild/easyblocks/t/tbb.py
Labels: bug fix

#1689 drop requirement for setuptools as runtime dependency
  .travis.yml
  easybuild/__init__.py
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/generic/__init__.py
Labels: change

#1691 make sure ~/.cache/pip isn't used while installing Tkinter
  easybuild/easyblocks/t/tkinter.py
Labels: bug fix, change

#1693 OpenBLAS with POWER support
  easybuild/easyblocks/o/openblas.py
Labels: enhancement, new

#1694 vtune: no license needed since 2019u3
  easybuild/easyblocks/v/vtune.py
Labels: enhancement

#1698 add support to PythonPackage to fix 'python' shebang lines in specified files to '#!/usr/bin/env python'
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#1701 set default exts_filter in PythonBundle, so already installed extensions in a bundle can be skipped
  easybuild/easyblocks/generic/pythonbundle.py
Labels: enhancement

#1705 also set $XDG_CACHE_HOME during installation of Python, to ensure that 'pip' that comes along with it doesn't touch $HOME/.cache/pip
  easybuild/easyblocks/p/python.py
Labels: bug fix

#1702 Handle new multi-deps python setup with $EBPYTHONPREFIXES for tensorflow
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#1704 Hopefully the final fix to make Bazel NOT use $HOME/.cache/bazel in TensorFlow
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1706 GROMACS - Use fp-model precise if FMA instructions are missing
  easybuild/easyblocks/g/gromacs.py
Labels: bug fix
