Repository easybuilders/easybuild-easyblocks, pull requests merged in 2019-09, with the labels that each got.

#1800 filter out empty entries in $CPATH or $C_INCLUDE_PATH when building Perl, since that breaks the build
  easybuild/easyblocks/p/perl.py
Labels: bug fix

#1786 vmd.py: Make the plugins build use the correct tcl library version.
  easybuild/easyblocks/v/vmd.py
Labels: bug fix

#1799 Add custom easyblock to install iccifort as self-contained software.
  easybuild/easyblocks/i/iccifort.py
  test/easyblocks/module.py
Labels: new

#1789 add custom easyblock for OpenMPI
  easybuild/easyblocks/o/openmpi.py
Labels: enhancement

#1801 fix sanity check command pattern for output of 'mpif90 --version' with PGI compilers
  easybuild/easyblocks/o/openmpi.py
Labels: bug fix

#1802 set $XDG_CACHE_HOME in TensorFlow easyblock to avoid that pip (ab)uses $HOME/.cache
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1791 Trilinos: use _MT_ libs for BLAS/LAPACK only if openmp is enabled.
  easybuild/easyblocks/t/trilinos.py
Labels: bug fix

#1788 enable 'check_ldshared' in generic PythonPackage easyblock by default
  easybuild/easyblocks/generic/pythonpackage.py
Labels: change

#1805 don't load modules for dependencies in CrayToolchain.prepare_step
  easybuild/easyblocks/generic/craytoolchain.py
Labels: bug fix

#1807 fix compatibility of XCrySDen easyblock with Python 3 (+ some cleanup)
  easybuild/easyblocks/x/xcrysden.py
Labels: bug fix

#1808 fix version checks in OpenFOAM easyblock that are not compatible with Python 3
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix

#1809 fix compatibility of NCL easyblock with Python 3 (+ some cleanup)
  easybuild/easyblocks/n/ncl.py
Labels: bug fix

#1810 update release notes & bump version for EasyBuild v4.0.0 release
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1812 release EasyBuild v4.0.0
  .travis.yml
  RELEASE_NOTES
  easybuild/__init__.py
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/aladin.py
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/c/cp2k.py
  easybuild/easyblocks/e/easybuildmeta.py
  easybuild/easyblocks/e/eigen.py
  easybuild/easyblocks/e/elpa.py
  easybuild/easyblocks/f/fftw.py
  easybuild/easyblocks/f/fsl.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/generic/__init__.py
  easybuild/easyblocks/generic/buildenv.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/craytoolchain.py
  easybuild/easyblocks/generic/intelbase.py
  easybuild/easyblocks/generic/makecp.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/generic/rpm.py
  easybuild/easyblocks/generic/systemcompiler.py
  easybuild/easyblocks/generic/systemmpi.py
  easybuild/easyblocks/i/icc.py
  easybuild/easyblocks/i/iccifort.py
  easybuild/easyblocks/i/imkl.py
  easybuild/easyblocks/l/libxml2.py
  easybuild/easyblocks/m/matlab.py
  easybuild/easyblocks/m/mcr.py
  easybuild/easyblocks/n/ncl.py
  easybuild/easyblocks/n/numexpr.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/p/paraver.py
  easybuild/easyblocks/p/pdt.py
  easybuild/easyblocks/p/perl.py
  easybuild/easyblocks/r/rosetta.py
  easybuild/easyblocks/s/score_p.py
  easybuild/easyblocks/s/shrimp.py
  easybuild/easyblocks/s/suitesparse.py
  easybuild/easyblocks/t/tbb.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/trilinos.py
  easybuild/easyblocks/v/vmd.py
  easybuild/easyblocks/w/wien2k.py
  easybuild/easyblocks/x/xcrysden.py
  setup.py
  test/easyblocks/general.py
  test/easyblocks/init_easyblocks.py
  test/easyblocks/module.py
  test/easyblocks/suite.py
Labels: update

#1813 sync with master and bump version to 4.0.1dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1811 enhance TensorFlow easyblock to support installing TF 1.14.0 with CUDA and MPI support
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1816 fix version check for TensorFlow 1.14.0
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1814 fix Boost easyblock for versions >=1.71.0
  easybuild/easyblocks/b/boost.py
Labels: update

#1817 avoid UnicodeDecodeError when reading 'configure' script and checking for 'Generated by GNU Autoconf' in ConfigureMake
  easybuild/easyblocks/generic/configuremake.py
Labels: bug fix

#1818 don't require 'python' command to install libxml2 without Python bindings
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/l/libxml2.py
Labels: bug fix

#1797 Setting a cudaarch template var so that it can be used in sources
  easybuild/easyblocks/c/cuda.py
Labels: enhancement

#1821 only read configure script when it's actually there in ConfigureMake easyblock
  easybuild/easyblocks/generic/configuremake.py
Labels: bug fix
