Repository easybuilders/easybuild-easyblocks, pull requests merged in 2019-05, with the labels that each got.

#1684 Make sure ldconfig can be found before using it.
  easybuild/easyblocks/c/cuda.py
Labels: bug fix

#1709 change default value for 'use_pip' to None, so we can discriminate from 'use_pip' being set to False explicitly
  easybuild/easyblocks/generic/pythonpackage.py
Labels: change

#1708 Make sure perl install dir follows a standard format
  easybuild/easyblocks/p/perl.py
Labels: bug fix

#1595 add custom easyblock for Blender
  easybuild/easyblocks/b/blender.py
Labels: new

#1713 avoid that --no-build-isolation option is specified multiple times
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#1711 Attach source_urls directly to sources for components in generic Bundle easyblock
  easybuild/easyblocks/generic/bundle.py
Labels: bug fix, change

#1715 make PythonPackage aware of (pre)testopts
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#1707 CHARMM - Add prebuildopts and runtest options
  easybuild/easyblocks/c/charmm.py
Labels: enhancement

#1314 enhance VMD easyblock to also build Surf & Stride + pick up netCDF for VMD >= 1.9.3
  easybuild/easyblocks/v/vmd.py
Labels: enhancement

#1716 Enable GPU offloading in Clang if CUDA is included as a dep
  easybuild/easyblocks/c/clang.py
Labels: enhancement

#1721 file() was removed in Python 3, use write_file() instead in Rosette easyblock
  easybuild/easyblocks/r/rosetta.py
Labels: python3

#1723 setup.py: Update the PyPI trove classifiers
  setup.py
Labels: bug fix, update

#1724 fix Python classifiers in setup.py, should be (only) Python 2.6 & 2.7
  setup.py
Labels: bug fix

#1725 add generic easyblock CMakeMakeCp
  easybuild/easyblocks/generic/cmakemakecp.py
Labels: new

#1726 clean up support for 'fix_python_shebang_for' in PythonPackage
  easybuild/easyblocks/generic/pythonpackage.py
Labels: change, code cleanup

#1728 use is_system_toolchain() rather than checking toolchain name against DUMMY_TOOLCHAIN_NAME constant
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/c/cp2k.py
  easybuild/easyblocks/e/eigen.py
  easybuild/easyblocks/generic/buildenv.py
  easybuild/easyblocks/generic/systemmpi.py
  easybuild/easyblocks/i/imkl.py
  easybuild/easyblocks/l/libxml2.py
  easybuild/easyblocks/p/pdt.py
  easybuild/easyblocks/s/score_p.py
  easybuild/easyblocks/t/tbb.py
Labels: bug fix, change, code cleanup

#1731 update Q&A patterns in SAS easyblock for version 9.4 + add support for custom license file path
  easybuild/easyblocks/s/sas.py
Labels: enhancement, update

#1692 update QuantumESPRESSO easyblock for v6.4.1
  easybuild/easyblocks/q/quantumespresso.py
Labels: update

#1727 fix prefix in impi compiler wrappers
  easybuild/easyblocks/i/impi.py
Labels: bug fix

#1697 make OpenBLAS easyblock set default build options + use custom sanity check
  easybuild/easyblocks/o/openblas.py
Labels: enhancement

#1717 add support to Clang easyblock for also building libc++ and RTTI
  easybuild/easyblocks/c/clang.py
Labels: enhancement

#1732 binutils: Only embed `zlib` if listed as a build dependency
  easybuild/easyblocks/b/binutils.py
Labels: change

#1730 rebuild internal libfabric for impi 2019.x & more recent
  easybuild/easyblocks/i/impi.py
Labels: enhancement

#1733 update release notes & bump version for EasyBuild v3.9.1 release
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1734 release EasyBuild v3.9.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/advisor.py
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/b/blender.py
  easybuild/easyblocks/c/cgal.py
  easybuild/easyblocks/c/charmm.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/f/fftw.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cmakemakecp.py
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/l/lua.py
  easybuild/easyblocks/o/openblas.py
  easybuild/easyblocks/p/perl.py
  easybuild/easyblocks/p/python.py
  easybuild/easyblocks/q/quantumespresso.py
  easybuild/easyblocks/s/sas.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/tkinter.py
  easybuild/easyblocks/v/vmd.py
  easybuild/easyblocks/v/vtune.py
  setup.py
Labels: update

#1736 sync with master + bump version to 3.9.2dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1621 Add custom easyblock for ELPA
  easybuild/easyblocks/e/elpa.py
Labels: new

#1737 update CPLEX sanity check: convert tool was removed in CPLEX 12.8
  easybuild/easyblocks/c/cplex.py
Labels: update

#1739 fix version check on using '-log' option to 'Allwmake' in OpenFOAM easyblock
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix
