Repository easybuilders/easybuild-easyblocks, pull requests merged in 2019-08, with the labels that each got.

#1775 Fix MSM easyblock
  easybuild/easyblocks/m/msm.py
Labels: code cleanup

#1776 MSM - Moved file copy and sanity check to easyblock
  easybuild/easyblocks/m/msm.py
Labels: enhancement

#1777 correctly define comp.src in Bundle easyblock, to fix compatibility with easyblocks that leverage self.src
  easybuild/easyblocks/generic/bundle.py
Labels: bug fix

#1778 fix Bundle.check_checksums to checksums for extensions are also checked
  easybuild/easyblocks/generic/bundle.py
Labels: bug fix

#1738 enhance CPLEX easyblock to also build Python bindings
  easybuild/easyblocks/c/cplex.py
Labels: enhancement

#1779 enhance sanity check for Blender to make sure that Cycles render engine is available
  easybuild/easyblocks/b/blender.py
Labels: enhancement

#1782 update release notes + bump version for EasyBuild v3.9.4
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1783 release EasyBuild v3.9.4
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/b/blender.py
  easybuild/easyblocks/c/cplex.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/m/matlab.py
  easybuild/easyblocks/m/msm.py
  easybuild/easyblocks/q/qt.py
  easybuild/easyblocks/w/wien2k.py
  easybuild/easyblocks/x/xcrysden.py
Labels: update

#1790 update Paraver easyblock to support recent versions
  easybuild/easyblocks/p/paraver.py
Labels: update

#1793 stop trying to use setuptools.setup in setup.py, always use distutils.core.setup instead
  .travis.yml
  setup.py
Labels: change

#1794 strip of leading 'v' from OpenFOAM version for version comparisons for compatibility with Python 3 (fixes #1792)
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix

#1773 removed checks for Boussinesq and sonic solvers for OpenFOAM 7, since those have been deprecated
  easybuild/easyblocks/o/openfoam.py
Labels: update

#1796 fix compatibility of SuiteSparse easyblock with Python 3
  easybuild/easyblocks/s/suitesparse.py
Labels: bug fix, python3

#1795 don't use sys.maxint in easyblocks (not compatible with Python 3)
  easybuild/easyblocks/c/cp2k.py
  test/easyblocks/init_easyblocks.py
Labels: bug fix, python3
