Repository easybuilders/easybuild-easyblocks, pull requests merged in 2019-06, with the labels that each got.

#1718 Allow Boost to build both Python2 and Python3 libraries
  easybuild/easyblocks/b/boost.py
Labels: enhancement

#1740 fix GROMACS easyblock for list-type configopts
  easybuild/easyblocks/g/gromacs.py
Labels: bug fix, enhancement

#1741 don't try to patch CROSSTOOL script for recent Bazel versions (since it's no longer there)
  easybuild/easyblocks/b/bazel.py
Labels: update

#1742 Fix configure step for GROMACS version < 4.6
  easybuild/easyblocks/g/gromacs.py
Labels: bug fix

#1746 update release notes & bump version for EasyBuild v3.9.2 release
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1747 release EasyBuild v3.9.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/b/bazel.py
  easybuild/easyblocks/b/boost.py
  easybuild/easyblocks/c/cplex.py
  easybuild/easyblocks/e/elpa.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/o/openfoam.py
Labels: update

#1748 sync with master + bump version to 3.9.3dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1751 stick to Ubuntu Trusty when testing with Python 2.6 in Travis
  .travis.yml
Labels: bug fix

#1757 only require vsc-base for EasyBuild 2.x and 3.x in EasyBuildMeta easyblock
  easybuild/easyblocks/e/easybuildmeta.py
Labels: update

#1752 healpix: easyblock updated to work with latest version of healpix configure.sh
  easybuild/easyblocks/h/healpix.py
Labels: enhancement

#1759 SNPhylo - Fix scripts installation path
  easybuild/easyblocks/s/snphylo.py
Labels: bug fix

#1761 be more patient when running interactive Allwmake.firstInstall command for recent OpenFOAM-Extend versions
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix
