Repository easybuilders/easybuild-easyblocks, pull requests merged in 2019-11, with the labels that each got.

#1843 fixes for TensorFlow easyblocks w.r.t. Bazel build options & __init__ in top-level google-protobuf package dir
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1842 SuperLU - move BLAS toolchain existence check earlier
  easybuild/easyblocks/s/superlu.py
Labels: bug fix

#1840 Minor fix to name of Gctf binary.
  easybuild/easyblocks/g/gctf.py
Labels: bug fix, priority:medium

#1838 add prebuildopts to bazel build command
  easybuild/easyblocks/b/bazel.py
Labels: enhancement

#1844 add GitHub Actions workflow to run easybuild-easyblocks test suite
  .github/workflows/unit_tests.yml
Labels: enhancement

#1848 change default value of files_to_copy to None in MakeCp generic easyblock + code cleanup & use change_dir, copy_dir, copy_file and mkdir function from filetools
  easybuild/easyblocks/generic/makecp.py
Labels: bug fix, code cleanup

#1837 New xmipp easyblock handling Xmipp based on Scons.
  easybuild/easyblocks/x/xmipp.py
Labels: enhancement, new

#1850 prepend -L$EBROOTZLIB/lib to LDFLAGS in SCOTCH easyblock
  easybuild/easyblocks/s/scotch.py
Labels: bug fix

#1849 add support to Toolchain generic easyblock for defining $EB* environment variables for toolchain components that use an external module
  easybuild/easyblocks/generic/toolchain.py
  test/easyblocks/easyblock_specific.py
  test/easyblocks/suite.py
Labels: enhancement

#1854 fix cuda header paths
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1845 fix support for sequential version in MUMPS easyblock
  easybuild/easyblocks/m/mumps.py
Labels: bug fix

#1855 cuDNN easyblock to allow for ppc64le
  easybuild/easyblocks/c/cudnn.py
Labels: new

#1853 add support for running 'pip check' during sanity check in generic PythonPackage easyblock
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#1852 Improved configuration for netcdf and netcdf4_python
  easybuild/easyblocks/n/netcdf.py
  easybuild/easyblocks/n/netcdf4_python.py
Labels: bug fix

#1861 handle incorrect regex better in generic CmdCp easyblock
  easybuild/easyblocks/generic/cmdcp.py
Labels: bug fix
