Repository easybuilders/easybuild-easyblocks, pull requests merged in 2019-12, with the labels that each got.

#1867 add missing docstrings in cmakeninja easyblock
  easybuild/easyblocks/generic/cmakeninja.py
Labels: bug fix

#1866 update release notes for EasyBuild v4.1.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1868 release EasyBuild v4.1.0
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/b/bazel.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/c/cudnn.py
  easybuild/easyblocks/g/gctf.py
  easybuild/easyblocks/generic/cmakeninja.py
  easybuild/easyblocks/generic/cmdcp.py
  easybuild/easyblocks/generic/makecp.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/generic/toolchain.py
  easybuild/easyblocks/m/mumps.py
  easybuild/easyblocks/n/netcdf.py
  easybuild/easyblocks/n/netcdf4_python.py
  easybuild/easyblocks/s/scotch.py
  easybuild/easyblocks/s/superlu.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/x/xmipp.py
  test/easyblocks/easyblock_specific.py
  test/easyblocks/suite.py
Labels: update

#1869 Make setup of cmake env usable from outside
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/o/openfoam.py
Labels: enhancement

#1872 sync develop with master and bump version to 4.1.1dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/generic/cmakeninja.py
  easybuild/easyblocks/x/xmipp.py
Labels: update

#1871 Fix CUDA EB for CUDA 10.1
  easybuild/easyblocks/c/cuda.py
Labels: bug fix

#1862 fix intel and netcdf libdirs in NCL easyblock
  easybuild/easyblocks/n/ncl.py
Labels: bug fix

#1882 disable running of 'sudo apt-get update' in GitHub CI config, since it's failing (and we don't really need it)
  .github/workflows/unit_tests.yml
Labels: bug fix, change

#1315 update WPS easyblock for v3.6 & newer
  easybuild/easyblocks/w/wps.py
Labels: enhancement

#1884 limit MPI ranks used for running WRF test cases to max. 4 + include contents of rsl.error.0000 output file in case test failed
  easybuild/easyblocks/w/wrf.py
Labels: bug fix

#1886 update WPS easyblock for recent versions: set $WRF_DIR to point to location of WRF installation
  easybuild/easyblocks/w/wps.py
Labels: update

#1860 update FSL easyblock to support FSL v6.0.2 & newer
  easybuild/easyblocks/f/fsl.py
Labels: update

#1889 update $PYTHONPATH + add "python -c 'import mrtrix3'" as sanity check command for recent MRtrix versions
  easybuild/easyblocks/m/mrtrix.py
Labels: bug fix

#1894 stop requiring Python dep for SWIG, just configure with --without-python if Python is not a dependency
  easybuild/easyblocks/s/swig.py
Labels: change

#1895 fix install dir subdir for WPS v4.0+ that is considered for $PATH and $LD_LIBRARY_PATH
  easybuild/easyblocks/w/wps.py
Labels: bug fix

#1891 make sure $PYTHONNOUSERSITE it set when performing sanity check for (bundles of) Python package(s)
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#1896 impi: don't rebuild libfabric if the source code is not present.
  easybuild/easyblocks/i/impi.py
Labels: bug fix

#1897 also copy component patches to self.cfg in Bundle generic easyblock
  easybuild/easyblocks/generic/bundle.py
Labels: bug fix

#1898 skip patch step in Bundle generic easyblock (per-component patches are still applied)
  easybuild/easyblocks/generic/bundle.py
Labels: bug fix

#1875 change Bazel easyblock to prefer using Java dependency rather than includued JDK (fix for POWER9)
  easybuild/easyblocks/b/bazel.py
Labels: bug fix

#1887 make sure $LIBLAPACK_MT is set before using it in ESMF easyblock
  easybuild/easyblocks/e/esmf.py
Labels: bug fix, code cleanup, enhancement

#1874 Add EasyBlock for cryptography to fix missing -pthread for all versions
  easybuild/easyblocks/c/cryptography.py
Labels: bug fix

#1880 openfoam: Small change to make Debug builds work correctly.
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix

#1890 update sanity check in SAMtools easyblock for version 1.10
  easybuild/easyblocks/s/samtools.py
Labels: bug fix, update

#1900 imkl: remove useless PATH entries, add PKG_CONFIG_PATH
  easybuild/easyblocks/i/imkl.py
Labels: change, enhancement
