Repository easybuilders/easybuild-easyblocks, pull requests merged in 2020-03, with the labels that each got.

#1906 update Trinity easyblock for v2.9.0
  easybuild/easyblocks/t/trinity.py
Labels: update

#1978 add cascadelake to KOKKOS_CPU_MAPPING in LAMMPS easyblock
  easybuild/easyblocks/l/lammps.py
Labels: enhancement

#1982 fix use of 'sorted' in LAMMPS easyblock
  easybuild/easyblocks/l/lammps.py
Labels: bug fix

#1981 fix sanity check for OpenFOAM-Extend >= 4.1
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix, update

#1980 add support for 'use_pip_extras' custom easyconfig parameter in PythonPackage easyblock
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#1956 update Ferret easyblock for versions >= 7.5.0
  easybuild/easyblocks/f/ferret.py
Labels: update

#1917 Fix MPI-CXX dependency of PETSc
  easybuild/easyblocks/p/petsc.py
Labels: bug fix, change

#1983 libdrm easyblock for custom sanity check on different architectures
  easybuild/easyblocks/l/libdrm.py
Labels: new

#1986 Fix patter matching in regex subst for I_MPI_ROOT
  easybuild/easyblocks/i/impi.py
Labels: bug fix

#1979 also set TRINITY_HOME environment variable in Trinity easyblock
  easybuild/easyblocks/t/trinity.py
Labels: bug fix

#1994 Fix "AttributeError: module 'git' has no attribute 'Git'"
  easybuild/easyblocks/__init__.py
Labels: bug fix

#1774 [parmetis] Make compatible with custom configopts
  easybuild/easyblocks/p/parmetis.py
Labels: enhancement

#1892 Change options based on arch for Mesa
  easybuild/easyblocks/m/mesa.py
Labels: new

#1997 Update lammps easyblock to be aware of MKL
  easybuild/easyblocks/l/lammps.py
Labels: enhancement

#1993 Use remove_dir instead of rmtree2
  easybuild/easyblocks/a/anaconda.py
  easybuild/easyblocks/g/go.py
  easybuild/easyblocks/generic/binary.py
  easybuild/easyblocks/generic/tarball.py
  easybuild/easyblocks/i/imkl.py
  easybuild/easyblocks/i/imod.py
  easybuild/easyblocks/m/mxnet.py
  easybuild/easyblocks/n/numpy.py
  easybuild/easyblocks/p/python_meep.py
  easybuild/easyblocks/t/trilinos.py
  easybuild/easyblocks/w/wien2k.py
Labels: enhancement

#1929 simplify various CMakeMake-based easyblocks by enhancing CMakeMake (w.r.t. CMAKE_BUILD_TYPE, shared vs static libs, fPIC)
  easybuild/easyblocks/a/armadillo.py
  easybuild/easyblocks/b/bamtools.py
  easybuild/easyblocks/b/blender.py
  easybuild/easyblocks/c/cgal.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/d/dirac.py
  easybuild/easyblocks/d/dolfin.py
  easybuild/easyblocks/e/eigen.py
  easybuild/easyblocks/e/elsi.py
  easybuild/easyblocks/g/gate.py
  easybuild/easyblocks/g/geant4.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/cmakepythonpackage.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/n/netcdf.py
  easybuild/easyblocks/o/openbabel.py
  easybuild/easyblocks/o/opencv.py
  easybuild/easyblocks/p/psi.py
  easybuild/easyblocks/r/root.py
  easybuild/easyblocks/s/superlu.py
  easybuild/easyblocks/t/trilinos.py
Labels: change, code cleanup
