Repository easybuilders/easybuild-easyblocks, pull requests merged in 2020-01, with the labels that each got.

#1902 add export to preinstallopts instead of install_script path in CUDA easyblock
  easybuild/easyblocks/c/cuda.py
Labels: bug fix

#1899 derive easyblock for iccifort only from icc easyblock (not ifort)
  easybuild/easyblocks/i/iccifort.py
Labels: bug fix

#1876 [Python] Remove obsolete configure args, build with optimizations + build with LTO for GCC >= 8.0
  easybuild/easyblocks/p/python.py
Labels: bug fix, enhancement, performance

#1904 iccifort: remove LIBRARY_PATH entries already known to icc et al
  easybuild/easyblocks/i/iccifort.py
Labels: bug fix, change

#1903 Don't set CPATH and LIBRARY_PATH any more for GCC and GCCcore.
  easybuild/easyblocks/g/gcc.py
Labels: change

#1907 use major/minor version of Python command being used if req_py_majver/req_py_minver are not specified
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#1908 define $EB_PYTHON in module for EasyBuild installation, to make sure correct Python version is used at runtime
  easybuild/easyblocks/e/easybuildmeta.py
Labels: bug fix

#1909 Allow Python 3.8 to be configured (Setup.dist script was renamed to Setup)
  easybuild/easyblocks/p/python.py
Labels: bug fix

#1911 fix netCDF easyblock for version 4.4.0
  easybuild/easyblocks/n/netcdf.py
Labels: bug fix

#1914 correct comment about when we set RUNPARALLEL in HDF5 easyblock
  easybuild/easyblocks/h/hdf5.py
Labels: bug fix

#1912 enhance tbb easyblock to support buuilding on POWER
  easybuild/easyblocks/t/tbb.py
Labels: enhancement

#1913 enhance TensorFlow easyblock to pick up on --cuda-compute-capabilities, and issue a warning if no CUDA compute capabilities are specified
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#1916 Do not sanity check on MATLAB compiler
  easybuild/easyblocks/m/matlab.py
Labels: change

#1915 add custom easyconfig parameter 'buildtype' to generic CMakeMake easyblock
  easybuild/easyblocks/generic/cmakemake.py
Labels: enhancement

#1919 [HDF5] Fix 'in' vs '==' confusion
  easybuild/easyblocks/h/hdf5.py
Labels: bug fix

#1922 rename 'buildtype' to 'build_type' in CMakeMake to purposely overwrite the ConfigureMake option with the same name
  easybuild/easyblocks/generic/cmakemake.py
Labels: change

#1923 ignore "Black would make changes" produced by flake8-black
  setup.cfg
Labels: change

#1924 override set_pylibdirs method in VersionIndependentPythonPackage to hard set self.pylibdir to 'lib'
  easybuild/easyblocks/generic/versionindependentpythonpackage.py
Labels: bug fix

#1836 fix for conda packages that rely on particular versions of Python
  easybuild/easyblocks/generic/conda.py
Labels: bug fix

#1926 update release notes for EasyBuild v4.1.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#1935 sync develop with master and bump version to 4.1.2dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update
