Repository easybuilders/easybuild-easyblocks, pull requests merged in 2020-12, with the labels that each got.

#2246 prepend all hardcoded /usr/* paths with sysroot in Python's setup.py installation script
  easybuild/easyblocks/p/python.py
Labels: EESSI, bug fix

#2250 fix setting of $RUNPARALLEL in h5py easyblock
  easybuild/easyblocks/h/hdf5.py
Labels: bug fix

#2230 enhance OpenMPI easyblock to catch any --with-ucx* configure options
  easybuild/easyblocks/o/openmpi.py
Labels: enhancement

#2266 use integer division to determine number MPI ranks to use in WRF test step
  easybuild/easyblocks/w/wrf.py
Labels: bug fix, python3

#2267 don't set $PYTHONNOUSERSITE in Python extension filter, it breaks some installations
  easybuild/easyblocks/p/python.py
Labels: bug fix

#2219 add custom easyblock for Metagenome-Atlas
  easybuild/easyblocks/m/metagenome_atlas.py
Labels: new

#2255 add custom easyblock for code-server
  easybuild/easyblocks/c/chimera.py
  easybuild/easyblocks/c/code_server.py
Labels: new

#2268 also specify locincpth and glibpth configure options for Perl based on --sysroot
  easybuild/easyblocks/p/perl.py
Labels: EESSI, bug fix

#2271 add support for ignoring numpy test result
  easybuild/easyblocks/n/numpy.py
Labels: enhancement

#2233 fix hardcoded path in NVHPC easyblock to support multiple architectures
  easybuild/easyblocks/n/nvhpc.py
Labels: bug fix

#2245 weed out duplicates when determining paths to include-fixed subdirectory
  easybuild/easyblocks/g/gcc.py
Labels: bug fix

#2275 add symbolic links for libwx_*so.0 files in wxPython installation
  easybuild/easyblocks/w/wxpython.py
Labels: bug fix

#2273 prepare release notes for EasyBuild v4.3.2 + bump version to 4.3.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2277 release EasyBuild v4.3.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/b/bazel.py
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/b/boost.py
  easybuild/easyblocks/c/chapel.py
  easybuild/easyblocks/c/chimera.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/c/code_server.py
  easybuild/easyblocks/c/cp2k.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/h/hdf5.py
  easybuild/easyblocks/i/icc.py
  easybuild/easyblocks/i/imkl.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/m/metagenome_atlas.py
  easybuild/easyblocks/n/ncl.py
  easybuild/easyblocks/n/numpy.py
  easybuild/easyblocks/n/nvhpc.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/p/perl.py
  easybuild/easyblocks/p/python.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/q/qt.py
  easybuild/easyblocks/q/quantumespresso.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/w/wrf.py
  easybuild/easyblocks/w/wxpython.py
Labels: update

#2278 sync with master + bump version to v4.3.3.dev0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2259 Create versioned symlinks for CMake commands + create symlink for 'cmake3' in PyTorch easyblock if cmake3 command is not found
  easybuild/easyblocks/c/cmake.py
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix, enhancement

#2280 prefer default value for extra options in easyblock tests
  test/easyblocks/init_easyblocks.py
Labels: enhancement

#2286 guard 'module unload' statements in modules for Cray* toolchains
  easybuild/easyblocks/generic/craytoolchain.py
Labels: change, enhancement

#2263 Add options to run unit tests to TensorFlow EasyBlock
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#2281 Unify handling of pylibdirs and don't add duplicated PYTHONPATH in PythonBundle
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#2287 rework module-only tests to use unique software name (rather than 'foo')
  easybuild/easyblocks/generic/modulerc.py
  test/easyblocks/module.py
Labels: bug fix

#2295 add custom easyblock for AOCC
  easybuild/easyblocks/a/aocc.py
Labels: new

#2292 set $TF_GPU_COUNT and $TF_TESTS_PER_GPU for TensorFlow tests
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement
