Repository easybuilders/easybuild-easyblocks, pull requests merged in 2020-10, with the labels that each got.

#2192 Update DIRAC easyblock for new easyconfigs
  easybuild/easyblocks/d/dirac.py
Labels: change

#2194 gamess_us.py: Minor update to handle option of building Michigan State University CCT3 & CCSD3A methods
  easybuild/easyblocks/g/gamess_us.py
Labels: enhancement

#2191 Make OpenBLAS respect the parallelism set by easybuild
  easybuild/easyblocks/o/openblas.py
Labels: enhancement

#2193 Add sanity check commands to clang and print warning for missing ncurses
  easybuild/easyblocks/c/clang.py
Labels: bug fix

#2197 leverage installed OpenSSL/BoringSSL when cURL is used as a dependency for TensorFlow
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#2198 remove unused custom easyblock for DIRAC
  easybuild/easyblocks/d/dirac.py
Labels: code cleanup

#2196 enhance OpenFOAM easyblock to add symlinks for libraries to ensure 'mpi' versions have preference over 'dummy' versions
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix

#1439 add easyblock for CFDEMcoupling
  easybuild/easyblocks/c/cfdemcoupling.py
Labels: new

#2203 add support to RubyGem easyblock for installing zipped gems
  easybuild/easyblocks/generic/rubygem.py
Labels: enhancement

#2204 add -ffree-line-length-none to gfortran flags in Siesta easyblock
  easybuild/easyblocks/s/siesta.py
Labels: bug fix

#2205 update ScaLAPACK easyblock to support installation with CMake for recent versions (>= v2.1.0)
  easybuild/easyblocks/s/scalapack.py
Labels: enhancement

#2190 add custom easyblock for NVHPC (aka PGI)
  easybuild/easyblocks/n/nvhpc.py
Labels: new

#2207 Respect --disable-mpi-tests in Siesta easyblock
  easybuild/easyblocks/s/siesta.py
Labels: bug fix

#2206 Score-P: Add support for NVHPC toolchain
  easybuild/easyblocks/s/score_p.py
Labels: enhancement

#2208 Only enable CUDA in LAMMPS if it is an explicit dep + add support for building for NVIDIA Ampere GPUs
  easybuild/easyblocks/l/lammps.py
Labels: bug fix

#2211 Revert "Only enable CUDA in LAMMPS if it is an explicit dep + add support for building for NVIDIA Ampere GPUs"
  easybuild/easyblocks/l/lammps.py
Labels: bug fix, change

#2210 prepare release notes for EasyBuild v4.3.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: documentation, update

#2214 release EasyBuild v4.3.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/c/cblas.py
  easybuild/easyblocks/c/cfdemcoupling.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/c/cmake.py
  easybuild/easyblocks/d/dirac.py
  easybuild/easyblocks/e/easybuildmeta.py
  easybuild/easyblocks/e/eigen.py
  easybuild/easyblocks/g/gamess_us.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/rubygem.py
  easybuild/easyblocks/m/mummer.py
  easybuild/easyblocks/n/nvhpc.py
  easybuild/easyblocks/o/openblas.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/q/qscintilla.py
  easybuild/easyblocks/s/scalapack.py
  easybuild/easyblocks/s/score_p.py
  easybuild/easyblocks/s/siesta.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/x/xml.py
Labels: update

#2216 sync with master + bump version to 4.3.2dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2217 pass paths to patch one by one to apply_regex_substitutions in GCC easyblock when --sysroot is set
  easybuild/easyblocks/g/gcc.py
Labels: EESSI, bug fix
