Repository easybuilders/easybuild-easyblocks, pull requests merged in 2020-07, with the labels that each got.

#2087 rename include-fixed subdirectory in GCC installation to avoid problems after OS upgrade
  easybuild/easyblocks/g/gcc.py
Labels: bug fix

#2088 use 'wclean -platform' instead of 'wcleanPlatform' for OpenFOAM v2006 & newer
  easybuild/easyblocks/o/openfoam.py
Labels: update

#2080 fix order of intel64/lib paths in generated module for impi (and drop intel64/lib/release_mt)
  easybuild/easyblocks/i/impi.py
Labels: bug fix

#2083 Make VMD easyblock Python 3 compatible
  easybuild/easyblocks/v/vmd.py
Labels: bug fix, python3

#2079 fix build environment for WRF by patching shebang in compile script
  easybuild/easyblocks/w/wrf.py
Labels: bug fix

#2056 only build OpenCV with IPP support on x86_64 systems
  easybuild/easyblocks/o/opencv.py
Labels: bug fix

#2062 make sure CFLAGS and MYCFLAGS are used in Lua easyblock
  easybuild/easyblocks/l/lua.py
Labels: bug fix

#2089 use glob pattern to determine name of Mathematica installation script
  easybuild/easyblocks/m/mathematica.py
Labels: bug fix, change

#2094 fix assumption in Bazel easyblock that include-fixed subdirectory is always there in GCC installation
  easybuild/easyblocks/b/bazel.py
Labels: bug fix

#2096 use mpirun for sanity check commands in LAMMPS easyblock
  easybuild/easyblocks/l/lammps.py
Labels: bug fix, change

#2097 removed version check against the version.txt file, since it is no lo…
  easybuild/easyblocks/c/cuda.py
Labels: change

#2091 prepare release notes for EasyBuild v4.2.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2098 release EasyBuild v4.2.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/b/bazel.py
  easybuild/easyblocks/d/dolfin.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/generic/intelbase.py
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/l/llvm.py
  easybuild/easyblocks/l/lua.py
  easybuild/easyblocks/m/mathematica.py
  easybuild/easyblocks/o/opencv.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/s/scipion.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/trilinos.py
  easybuild/easyblocks/v/vmd.py
  easybuild/easyblocks/w/wrf.py
  easybuild/easyblocks/x/xalt.py
Labels: update

#2099 sync develop with master + bump version to 4.2.3dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2085 Tensorflow.py fails with bigger NCCL version names
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#2100 add support for v1.3.2 to motioncor2
  easybuild/easyblocks/m/motioncor2.py
Labels: enhancement

#2101 filter out Python in SLEPc configure
  easybuild/easyblocks/s/slepc.py
Labels: change

#2107 patch ELPA's manual_cpp script to fix hardcoded /usr/bin/python
  easybuild/easyblocks/e/elpa.py
Labels: bug fix

#2106 Fix MPI in netcdf4_python easyblock
  easybuild/easyblocks/n/netcdf4_python.py
Labels: update
