Repository easybuilders/easybuild-easyblocks, pull requests merged in 2020-02, with the labels that each got.

#1952 openblas: remove tests from build_step and raise error on failed tests
  easybuild/easyblocks/o/openblas.py
Labels: bug fix, enhancement

#1955 openblas: add lexming as author
  easybuild/easyblocks/o/openblas.py
Labels: change

#1958 openblas: add optional runtest to the catch for FATAL ERRORS
  easybuild/easyblocks/o/openblas.py
Labels: bug fix

#1961 ensure right 'python' command is used to determine Python lib dir when system Python is used with PythonBundle easyblock
  easybuild/easyblocks/generic/pythonbundle.py
Labels: bug fix

#1951 add easyblock for BerkeleyGW
  easybuild/easyblocks/b/berkeleygw.py
Labels: new

#1944 [TensorFlow] Disable ROCM and Android workspace explicitely
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#1943 get_tbb_gccprefix: support GCCcore and gcc4.8 (if that dir exists)
  easybuild/easyblocks/i/icc.py
  easybuild/easyblocks/t/tbb.py
Labels: bug fix

#1962 reinstate parallel building of OpenBLAS
  easybuild/easyblocks/o/openblas.py
Labels: bug fix

#1947 update QE easyblock for version 6.5
  easybuild/easyblocks/q/quantumespresso.py
Labels: enhancement

#1960 openblas: pass any TARGET in buildopts to testopts and installopts
  easybuild/easyblocks/o/openblas.py
Labels: enhancement

#1959 update XCrySDen easyblock to support Togl dependency
  easybuild/easyblocks/x/xcrysden.py
Labels: enhancement

#1883 add easyblock for ELSI
  easybuild/easyblocks/e/elsi.py
Labels: new

#1954 update SIESTA easyblock to support MaX-1.0 release
  easybuild/easyblocks/s/siesta.py
Labels: enhancement

#1936 Add EasyBlock for CMake
  easybuild/easyblocks/c/cmake.py
Labels: new

#1934 [TensorFlow] Limit amount of parallelism
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1950 Restore default flake8 warnings
  setup.cfg
Labels: bug fix

#1968 force building Clang without CUDA when not found in EB
  easybuild/easyblocks/c/clang.py
Labels: change

#1971 also specify location to netCDF-Fortran include files in Siesta easyblock
  easybuild/easyblocks/s/siesta.py
Labels: bug fix

#1964 add custom easyblock for LAMMPS
  .gitignore
  easybuild/easyblocks/l/lammps.py
Labels: new

#1976 use checkout@v2 in GitHub Actions to fix broken re-triggered tests
  .github/workflows/unit_tests.yml
Labels: bug fix

#1974 [CMake] Handle configopts without configure args
  easybuild/easyblocks/c/cmake.py
Labels: bug fix

#1973 add NCDF_PARALLEL and METIS support to Siesta easyblock
  easybuild/easyblocks/s/siesta.py
Labels: enhancement
