Repository easybuilders/easybuild-easyblocks, pull requests merged in 2020-08, with the labels that each got.

#2110 make TensorFlow easyblock also set $GCC_HOST_COMPILER_PREFIX to specify binutils location
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#2105 handle GNUInstallDirs /opt special case in CMakeMake easyblock
  easybuild/easyblocks/generic/cmakemake.py
Labels: bug fix

#2102 tinker.py: Handle skipping of tests depending on version. Link with fftw_omp since the code uses openmp.
  easybuild/easyblocks/t/tinker.py
Labels: enhancement

#2077 added multi_deps support into qscintilla easyblock
  easybuild/easyblocks/q/qscintilla.py
Labels: enhancement

#2114 ensure stand-alone Python package being installed is in view when running 'pip check' by loading fake module first
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#2113 Allow NAMD to be built on POWER, and also use the CUDA arch info
  easybuild/easyblocks/n/namd.py
Labels: enhancement

#2116 update Libint easyblock for versions >= 2.6.0 + add custom easyconfig parameter to enable Fortran support
  easybuild/easyblocks/l/libint.py
Labels: update

#2069 update CP2K easyblock for recent versions (>= 7.0)
  easybuild/easyblocks/c/cp2k.py
Labels: update

#2115 Add EasyBlock for Pybind11
  easybuild/easyblocks/p/pybind11.py
Labels: new

#2118 add support in NAMD easyblock to pass additional C++ compiler options for building Charm++ component with + wrap them in single quotes
  easybuild/easyblocks/n/namd.py
Labels: bug fix, enhancement

#2119 be more patient when running interactive configure script for WRF
  easybuild/easyblocks/w/wrf.py
Labels: bug fix

#2124 extend GNUInstallDirs special cases in CMakeMake easyblock
  easybuild/easyblocks/generic/cmakemake.py
Labels: enhancement

#2058 Use new MATLAB binary installer for versions >= 2020a
  easybuild/easyblocks/m/matlab.py
Labels: update

#2126 switch to status badge based on tests run in GitHub Actions CI in README
  README.rst
Labels: change, documentation

#2120 automatically add required -G Ninja when using CMakeNinja easyblock + add 'generator' custom easyconfig parameter for CMakeMake
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/cmakeninja.py
Labels: enhancement

#2128 [Flake8] Clean easybuild/easyblocks/a
  easybuild/easyblocks/a/abaqus.py
  easybuild/easyblocks/a/advisor.py
  easybuild/easyblocks/a/aladin.py
  easybuild/easyblocks/a/allinea.py
  easybuild/easyblocks/a/amber.py
  easybuild/easyblocks/a/anaconda.py
  easybuild/easyblocks/a/ansys.py
  easybuild/easyblocks/a/arb.py
  easybuild/easyblocks/a/armadillo.py
  easybuild/easyblocks/a/atlas.py
Labels: code cleanup

#2129 fix code style issues in b*/.py and c/*.py
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/b/bioconductor.py
  easybuild/easyblocks/b/bisearch.py
  easybuild/easyblocks/b/blacs.py
  easybuild/easyblocks/b/blender.py
  easybuild/easyblocks/b/boost.py
  easybuild/easyblocks/b/bowtie2.py
  easybuild/easyblocks/b/bwa.py
  easybuild/easyblocks/b/bzip2.py
  easybuild/easyblocks/c/cblas.py
  easybuild/easyblocks/c/cgal.py
  easybuild/easyblocks/c/chapel.py
  easybuild/easyblocks/c/charmm.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/c/comsol.py
  easybuild/easyblocks/c/cp2k.py
  easybuild/easyblocks/c/cppcheck.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/c/cufflinks.py
Labels: code cleanup

#2130 fix code style issues in d/*.py
  easybuild/easyblocks/d/db.py
  easybuild/easyblocks/d/dl_poly_classic.py
  easybuild/easyblocks/d/dolfin.py
  easybuild/easyblocks/d/doris.py
  easybuild/easyblocks/d/doxygen.py
Labels: code cleanup

#2132 fix code style issues in generic/*.py
  easybuild/easyblocks/generic/binariestarball.py
  easybuild/easyblocks/generic/binary.py
  easybuild/easyblocks/generic/buildenv.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/cmakepythonpackage.py
  easybuild/easyblocks/generic/conda.py
  easybuild/easyblocks/generic/configuremakepythonpackage.py
  easybuild/easyblocks/generic/craytoolchain.py
  easybuild/easyblocks/generic/packedbinary.py
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/generic/rpm.py
Labels: code cleanup

#2136 fix code style issues in n/*.py
  easybuild/easyblocks/n/namd.py
  easybuild/easyblocks/n/ncl.py
  easybuild/easyblocks/n/ncurses.py
  easybuild/easyblocks/n/netcdf.py
  easybuild/easyblocks/n/netcdf_fortran.py
  easybuild/easyblocks/n/neuron.py
  easybuild/easyblocks/n/numpy.py
  easybuild/easyblocks/n/nwchem.py
Labels: code cleanup

#2131 fix code style issues in e/*.py through g/*.py
  easybuild/easyblocks/e/eigen.py
  easybuild/easyblocks/e/elpa.py
  easybuild/easyblocks/e/elsi.py
  easybuild/easyblocks/e/epd.py
  easybuild/easyblocks/e/espresso.py
  easybuild/easyblocks/e/extrae.py
  easybuild/easyblocks/f/fdtd_solutions.py
  easybuild/easyblocks/f/ferret.py
  easybuild/easyblocks/f/flex.py
  easybuild/easyblocks/f/fluent.py
  easybuild/easyblocks/f/foldx.py
  easybuild/easyblocks/f/freesurfer.py
  easybuild/easyblocks/f/freetype.py
  easybuild/easyblocks/g/g2clib.py
  easybuild/easyblocks/g/g2lib.py
  easybuild/easyblocks/g/gamess_us.py
  easybuild/easyblocks/g/gate.py
  easybuild/easyblocks/g/geant4.py
  easybuild/easyblocks/g/ghc.py
  easybuild/easyblocks/g/go.py
  easybuild/easyblocks/g/gromacs.py
Labels: code cleanup

#2133 fix code style issues in h/*.py through l/*.py
  easybuild/easyblocks/h/hadoop.py
  easybuild/easyblocks/h/hdf5.py
  easybuild/easyblocks/h/healpix.py
  easybuild/easyblocks/h/hpcg.py
  easybuild/easyblocks/h/hpl.py
  easybuild/easyblocks/i/icc.py
  easybuild/easyblocks/i/ifort.py
  easybuild/easyblocks/i/imkl.py
  easybuild/easyblocks/i/imod.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/i/ipp.py
  easybuild/easyblocks/i/itac.py
  easybuild/easyblocks/l/lapack.py
  easybuild/easyblocks/l/libqglviewer.py
  easybuild/easyblocks/l/libsmm.py
  easybuild/easyblocks/l/libxml2.py
Labels: code cleanup

#2135 make flake8 code style checks pass in w/*.py
  easybuild/easyblocks/w/wien2k.py
  easybuild/easyblocks/w/wps.py
  easybuild/easyblocks/w/wrf.py
  easybuild/easyblocks/w/wrf_fire.py
  easybuild/easyblocks/w/wxpython.py
Labels: code cleanup

#2138 correctly check whether 'modinc' easyconfig parameter is set to True in CP2K easyblock
  easybuild/easyblocks/c/cp2k.py
Labels: bug fix

#2134 fix code style issues in m/*.py
  easybuild/easyblocks/m/maple.py
  easybuild/easyblocks/m/mesa.py
  easybuild/easyblocks/m/metavelvet.py
  easybuild/easyblocks/m/metis.py
  easybuild/easyblocks/m/modeller.py
  easybuild/easyblocks/m/molpro.py
  easybuild/easyblocks/m/mono.py
  easybuild/easyblocks/m/mothur.py
  easybuild/easyblocks/m/mpich.py
  easybuild/easyblocks/m/mtl4.py
  easybuild/easyblocks/m/mumps.py
  easybuild/easyblocks/m/mxnet.py
Labels: code cleanup

#2137 make flake8 code style checks pass in o/*.py through v/*.py + other *.py files in repo
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/o/octave.py
  easybuild/easyblocks/o/openifs.py
  easybuild/easyblocks/o/openssl.py
  easybuild/easyblocks/p/parmetis.py
  easybuild/easyblocks/p/pasha.py
  easybuild/easyblocks/p/pbdmpi.py
  easybuild/easyblocks/p/pbdslap.py
  easybuild/easyblocks/p/petsc.py
  easybuild/easyblocks/p/pgi.py
  easybuild/easyblocks/p/primer3.py
  easybuild/easyblocks/p/psmpi.py
  easybuild/easyblocks/p/pyquante.py
  easybuild/easyblocks/p/pyzmq.py
  easybuild/easyblocks/q/qscintilla.py
  easybuild/easyblocks/q/qt.py
  easybuild/easyblocks/r/__init__.py
  easybuild/easyblocks/r/r.py
  easybuild/easyblocks/r/rmpi.py
  easybuild/easyblocks/r/rosetta.py
  easybuild/easyblocks/r/ruby.py
  easybuild/easyblocks/s/samtools.py
  easybuild/easyblocks/s/sas.py
  easybuild/easyblocks/s/scalapack.py
  easybuild/easyblocks/s/scotch.py
  easybuild/easyblocks/s/siesta.py
  easybuild/easyblocks/s/snphylo.py
  easybuild/easyblocks/s/soapdenovo.py
  easybuild/easyblocks/s/stata.py
  easybuild/easyblocks/s/suitesparse.py
  easybuild/easyblocks/t/tau.py
  easybuild/easyblocks/t/tornado.py
  easybuild/easyblocks/t/totalview.py
  easybuild/easyblocks/t/trilinos.py
  easybuild/easyblocks/t/trinity.py
  easybuild/easyblocks/u/ufc.py
  easybuild/easyblocks/v/velvet.py
  setup.py
  test/__init__.py
  test/easyblocks/general.py
  test/easyblocks/init_easyblocks.py
  test/easyblocks/module.py
Labels: code cleanup

#2140 Enable flake8 on CI
  .github/workflows/linting.yml
Labels: code cleanup

#2123 fix default value for custom 'namd_basearch' easyconfig parameter in NAMD easyblock
  easybuild/easyblocks/n/namd.py
Labels: bug fix

#2142 make Perl easyblock aware of --sysroot EasyBuild configuration option
  easybuild/easyblocks/p/perl.py
Labels: enhancement

#2084 fix Mothur easyblock to work with 1.44.0 and higher
  easybuild/easyblocks/m/mothur.py
Labels: update

#2064 added option use_pip_requirement to allow providing a requirements file to the pip command, as a source
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#2144 fix running GROMACS tests when using 'eb --rpath'
  easybuild/easyblocks/g/gromacs.py
Labels: EESSI, bug fix

#2143 make GCC easyblock aware of --sysroot EasyBuild configuration option
  easybuild/easyblocks/g/gcc.py
Labels: EESSI, enhancement

#2146 remove existing Python installation directory if both 'eb --rpath' and --enable-optimizations configuration parameter are used
  easybuild/easyblocks/p/python.py
Labels: bug fix

#2148 patch setup.py when installing Python with 'eb --sysroot=...' to fix issues with building of _ssl module
  easybuild/easyblocks/p/python.py
Labels: EESSI, bug fix

#2145 fix call to os.path.join in sanity checks of netcdf easyblock
  easybuild/easyblocks/n/netcdf.py
Labels: bug fix

#2147 take --sysroot EasyBuild configuration option into account in binutils easyblock
  easybuild/easyblocks/b/binutils.py
Labels: EESSI, enhancement
