Repository easybuilders/easybuild-easyblocks, pull requests merged in 2020-09, with the labels that each got.

#2151 ensure libQt5Core.so is compatible with older Linux kernels by disabling renameat2 and getentropy features
  easybuild/easyblocks/q/qt.py
Labels: EESSI, bug fix

#2149 fix patching of hardcoded paths in Python's setup.py for older Python versions when EasyBuild is configured with --sysroot
  easybuild/easyblocks/p/python.py
Labels: EESSI, bug fix

#2152 set -DCMAKE_SYSROOT based on --sysroot EasyBuild configuration setting, and auto-enable using full path to compiler commands when doing so
  easybuild/easyblocks/generic/cmakemake.py
Labels: EESSI, enhancement

#2108 handle installation of pip & setuptools in Python 3.4+
  easybuild/easyblocks/p/python.py
Labels: enhancement

#2103 add 'lib' symlink in tbb installation directory when building from source
  easybuild/easyblocks/t/tbb.py
Labels: bug fix

#2155 remove duplicate empty line in tbb easyblock which makes code linter check fail
  easybuild/easyblocks/t/tbb.py
Labels: bug fix, code cleanup

#2153 make Mesa easyblock aware of aarch64
  easybuild/easyblocks/m/mesa.py
Labels: bug fix

#2154 take existing 'lib' subdir into account when copying it to test GROMACS installation
  easybuild/easyblocks/g/gromacs.py
Labels: EESSI, bug fix

#2159 avoid setting sysroot to None in binutils easyblock
  easybuild/easyblocks/b/binutils.py
Labels: bug fix

#2158 Solve issue where pybind11 picks up on the system Python instead of one provided by a module
  easybuild/easyblocks/p/pybind11.py
Labels: bug fix

#2117 Make TensorFlow use system/EasyBuild installed libraries
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#2125 make sure self.start_dir is set to a full path before constructing installation command in RPackage easyblock
  easybuild/easyblocks/generic/rpackage.py
Labels: bug fix

#2163 fix Python package detection in TensorFlow easyblock and improve warning message
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#2104 add custom easyblock for PyTorch
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/p/pytorch.py
Labels: new

#2160 fix Qt5 easyblock to support installation on Arm/aarch64 (requires platform to be linux-g++)
  easybuild/easyblocks/q/qt.py
Labels: aarch64, bug fix

#2162 fix OpenFOAM easyblock to support installation on Arm/aarch64 systems
  easybuild/easyblocks/o/openfoam.py
Labels: aarch64

#2141 update PSI easyblock to correctly find Python and enable PCMSolver/CheMPS2
  easybuild/easyblocks/p/psi.py
Labels: bug fix

#2164 explicitely enable/disable CUDA options in PyTorch easyblock + fix download check in sanity check + fix for disabling of *NNPACK on POWER systems
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix

#2112 update QuantumESPRESSO easyblock to support version 6.6
  easybuild/easyblocks/q/quantumespresso.py
Labels: update

#2165 update TensorFlow easyblock to support installing TensorFlow 2.0 with dependencies provided through EasyBuild
  easybuild/easyblocks/t/tensorflow.py
Labels: update

#2168 fix sanity check in Mathematica easyblock for 11.x versions older than 11.3
  easybuild/easyblocks/m/mathematica.py
Labels: bug fix

#2169 unset $COLUMNS if it is set to '0' before running Perl's configure script
  easybuild/easyblocks/p/perl.py
Labels: bug fix

#2171 enhance sanity check in custom Doxygen easyblock to catch broken installation
  easybuild/easyblocks/d/doxygen.py
Labels: enhancement

#2172 improve workaround for JsonCpp dependency in TensorFlow easyblock
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix, change

#2170 prepare release notes for EasyBuild v4.3.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2174 sync with master + bump version to 4.3.0dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2175 updated CBLAS easyblock for toolchains that include imkl
  easybuild/easyblocks/c/cblas.py
Labels: enhancement

#2182 Added XLA build support
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#2183 Set LD_LIBRARY_PATH to PyTorch lib folder
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix

#2184 also consider libfabric dep (--with-ofi) when setting default OpenMPI configure options
  easybuild/easyblocks/o/openmpi.py
Labels: enhancement

#2181 Enable CTEST_OUTPUT_ON_FAILURE for CMake test_step
  easybuild/easyblocks/generic/cmakemake.py
Labels: enhancement

#2176 Workaround duplicate prefix path in Eigen CMake config
  easybuild/easyblocks/e/eigen.py
Labels: bug fix

#2166 update TensorFlow easyblock to put Bazel build files in build directory + avoid unnecessary runtime patching
  easybuild/easyblocks/t/tensorflow.py
Labels: change, enhancement

#2109 set $EB_INSTALLPYTHON in module generated for EasyBuild rather than setting $EB_PYTHON, to allow overriding Python command to be used for running EasyBuild with $EB_PYTHON
  easybuild/easyblocks/e/easybuildmeta.py
Labels: change

#2187 make easyblock for installing CMake aware of --sysroot
  easybuild/easyblocks/c/cmake.py
Labels: EESSI, bug fix, enhancement

#2040 support having pyqt installed as part of Qt5
  easybuild/easyblocks/q/qscintilla.py
Labels: enhancement

#2188 configure OpenMPI 4.x with --without-verbs when using UCX
  easybuild/easyblocks/o/openmpi.py
Labels: bug fix

#2185 update MUMmer easyblock to use apply_regex_substitutions and copy_file functions
  easybuild/easyblocks/m/mummer.py
Labels: bug fix, code cleanup

#2189 take into account that zlib may be listed in --filter-deps in custom easyblock for XML R package
  easybuild/easyblocks/x/xml.py
Labels: EESSI, bug fix
