Repository easybuilders/easybuild-easyblocks, pull requests merged in 2020-05, with the labels that each got.

#2050 gitignore .mypy_cache dirs
  .gitignore
Labels: change

#2051 don't let extract_file change directory in various easyblocks
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/n/namd.py
  easybuild/easyblocks/p/python_meep.py
  easybuild/easyblocks/r/rosetta.py
  easybuild/easyblocks/v/vmd.py
  easybuild/easyblocks/w/wien2k.py
  easybuild/easyblocks/w/wps.py
Labels: bug fix, change

#2033 Use config.guess for GCC builds
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/generic/configuremake.py
Labels: bug fix, enhancement

#2045 impi: execute minimal test in sanity check commands
  easybuild/easyblocks/i/impi.py
Labels: enhancement

#2047 clean $CPATH before building ROOT to avoid clash between external LLVM loaded as a dependency and internal LLVM used by ROOT
  easybuild/easyblocks/r/root.py
Labels: bug fix

#2021 add custom 'subdir_version' easyconfig parameter for FLUENT
  easybuild/easyblocks/f/fluent.py
Labels: enhancement

#2044 [binutils] Include own lib dir in rpath before system lib dirs
  easybuild/easyblocks/b/binutils.py
Labels: bug fix

#2055 correct download url for test data in WPS easyblock
  easybuild/easyblocks/w/wps.py
Labels: bug fix

#2059 fix failing sanity check for GCCcore 5.x + sanity check under --module-only for all GCCcore versions
  easybuild/easyblocks/g/gcc.py
Labels: bug fix

#2057 Fix typo in warning
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#2053 FreeSurfer: fix the extra dirs added to PATH
  easybuild/easyblocks/f/freesurfer.py
Labels: bug fix

#1949 Update config.guess for all R packages
  easybuild/easyblocks/generic/configuremake.py
  easybuild/easyblocks/generic/rpackage.py
Labels: change, enhancement

#1991 rewrite GROMACS easyblock to build all four variations in the same build
  easybuild/easyblocks/g/gromacs.py
Labels: enhancement, feature

#2029 generically find the arch folder and add top-level bin/lib symlinks in PDT & TAU easyblocks
  easybuild/easyblocks/p/pdt.py
  easybuild/easyblocks/t/tau.py
Labels: bug fix, enhancement

#2052 make postinstallcmds available to Mathematica easyconfigs + add bin/Executables to $PATH
  easybuild/easyblocks/m/mathematica.py
Labels: bug fix

#2032 let CMakeMake remove 'easybuild_obj' build directory if it already exists
  easybuild/easyblocks/generic/cmakemake.py
Labels: bug fix, change

#2060 bump version and update release notes for EasyBuild v4.2.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: documentation, update

#2061 release EasyBuild 4.2.1
  .gitignore
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/b/blender.py
  easybuild/easyblocks/c/cplex.py
  easybuild/easyblocks/f/fluent.py
  easybuild/easyblocks/f/freesurfer.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/configuremake.py
  easybuild/easyblocks/generic/gopackage.py
  easybuild/easyblocks/generic/rpackage.py
  easybuild/easyblocks/generic/tarball.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/m/mathematica.py
  easybuild/easyblocks/m/motioncor2.py
  easybuild/easyblocks/n/namd.py
  easybuild/easyblocks/n/nwchem.py
  easybuild/easyblocks/p/pdt.py
  easybuild/easyblocks/p/petsc.py
  easybuild/easyblocks/p/python_meep.py
  easybuild/easyblocks/q/quantumespresso.py
  easybuild/easyblocks/r/root.py
  easybuild/easyblocks/r/rosetta.py
  easybuild/easyblocks/s/score_p.py
  easybuild/easyblocks/t/tau.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/v/vmd.py
  easybuild/easyblocks/w/wien2k.py
  easybuild/easyblocks/w/wps.py
  test/easyblocks/module.py
Labels: update

#2063 sync develop with master + bump version to 4.2.2dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2065 new easyblock for LLVM
  easybuild/easyblocks/l/llvm.py
Labels: new

#1942 Add XALT EasyBlock
  easybuild/easyblocks/x/xalt.py
Labels: new
