Repository easybuilders/easybuild-easyblocks, pull requests merged in 2020-04, with the labels that each got.

#1933 enable out of tree build by default in CMakeMake easyblock
  easybuild/easyblocks/generic/cmakemake.py
Labels: change

#2006 take into account user defined gallium_drivers and swr_arches in Mesa easyblock
  easybuild/easyblocks/m/mesa.py
Labels: enhancement

#2005 make sure libxml2 is built with XZ provided as dependency
  easybuild/easyblocks/l/libxml2.py
Labels: bug fix

#2000 QtWebEngine is not fully supported on POWER - so do not sanity check it
  easybuild/easyblocks/q/qt.py
Labels: bug fix

#1970 in version 6.0 of TensorRT, libnvinfer.a is renamed libnvinfer_static.a
  easybuild/easyblocks/t/tensorrt.py
Labels: bug fix

#1975 add EPYC to KOKKOS_CPU_ARCH_LIST and MAPPING in LAMMPS easyblock
  easybuild/easyblocks/l/lammps.py
Labels: enhancement

#1995 Allow differing names for TF wheel
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#2002 Fix TensorFlow in some environments
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1966 make sure lib/python*/lib-dynload exists in Python installation
  easybuild/easyblocks/p/python.py
Labels: bug fix

#2015 use apt-spy2 before using apt in GitHub Actions
  .github/workflows/unit_tests.yml
Labels: bug fix, change

#2014 Update the contributing docs
  CONTRIBUTING.md
Labels: bug fix

#2008 make MATLAB runtime available from MATLAB
  easybuild/easyblocks/m/matlab.py
Labels: enhancement

#2013 Enable TK, FLTK and OPENGL in VMD config (deps already present)
  easybuild/easyblocks/v/vmd.py
Labels: bug fix

#1998 Added SEPP easyblock.
  easybuild/easyblocks/s/sepp.py
Labels: new

#2018 stop using apt-spy2 to pick an alternative mirror, it's expensive and may result in picking a faulty mirror...
  .github/workflows/unit_tests.yml
Labels: bug fix, change

#2020 fix version check in TensorFlow easyblock
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#1977 don't insist that pylibdir always exists in OpenCV easyblock
  easybuild/easyblocks/o/opencv.py
Labels: bug fix, change

#1992 update Open Babel easyblock for version 3.0.0
  easybuild/easyblocks/o/openbabel.py
Labels: enhancement

#1885 fix linking of Hypre to external BLAS/LAPACK + support building (only) static/shared library
  easybuild/easyblocks/h/hypre.py
Labels: bug fix, change

#2022 fix numexpr easyblock to allow (correct) installing it as extension
  easybuild/easyblocks/n/numexpr.py
Labels: bug fix

#2010 look for Python version directories with suffixes in ROOT easyblock
  easybuild/easyblocks/r/root.py
Labels: bug fix

#2025 bump version and update release notes for EasyBuild v4.2.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: documentation

#2028 sync develop with master after EasyBuild v4.2.0 release + bump version to 4.2.1dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2031 fix typo in LAMMPS easyblock preventing disabling the USER-INTEL package via configopts
  easybuild/easyblocks/l/lammps.py
Labels: bug fix

#2027 use correct version in ELPA preprocessor flag used for QuantumESPRESSO v6.x
  easybuild/easyblocks/q/quantumespresso.py
Labels: bug fix, update

#1989 tarball: add support for preinstallopts and install in subdirectory
  easybuild/easyblocks/generic/tarball.py
Labels: enhancement

#2030 add more configure option for dependencies in Score-P easyblock
  easybuild/easyblocks/s/score_p.py
Labels: change, enhancement

#2038 add extra question pattern to support installing CPLEX 12.10
  easybuild/easyblocks/c/cplex.py
Labels: update

#2043 add support for building NWChem on top of external GlobalArrays + also define $LAPACK_LIB (required for NWChem 7.x)
  easybuild/easyblocks/n/nwchem.py
Labels: enhancement, update

#2042 Add GoPackage EasyBlock
  easybuild/easyblocks/generic/gopackage.py
  test/easyblocks/module.py
Labels: new

#2048 fixes/enhancements for PETSc easyblock
  easybuild/easyblocks/p/petsc.py
Labels: bug fix, enhancement

#2037 Remove local find_glob_pattern; use new version from filetools instead
  easybuild/easyblocks/b/blender.py
  easybuild/easyblocks/r/root.py
Labels: change, code cleanup

#2049 raise error when unknown 'install_type' is used in Tarball easyblock + fix log messages
  easybuild/easyblocks/generic/tarball.py
Labels: bug fix, change
