Repository easybuilders/easybuild-easyblocks, pull requests merged in 2021-02, with the labels that each got.

#2327 Fixup comment regarding RPATH in binutils easyblock
  easybuild/easyblocks/b/binutils.py
Labels: bug fix

#2293 create less temporary directories for TensorFlow by (only) using --output_user_root
  easybuild/easyblocks/t/tensorflow.py
Labels: change

#2320 Fix OpenFOAM sanity check on POWER
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix

#2321 Added support for OpenFOAM v2012 layout
  easybuild/easyblocks/o/openfoam.py
Labels: update

#2325 pass down compilation flags from build environment for ESMF
  easybuild/easyblocks/e/esmf.py
Labels: bug fix, enhancement

#2330 Making symlinking of posix_c.so to posix.so in test suite configuration conditional
  .github/workflows/unit_tests.yml
Labels: bug fix, tests

#2290 add support for skipping steps in Python packages installed as extension + print progress on individual steps for installing Python packages as extensions
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#2314 Update optional feature support of TensorFlow
  easybuild/easyblocks/t/tensorflow.py
Labels: update

#2312 Add support for running TensorFlow CPU and GPU tests separately and enhance test failure reporting
  easybuild/easyblocks/t/tensorflow.py
Labels: change, enhancement

#2334 update FLUENT sanity check for v2021R1
  easybuild/easyblocks/f/fluent.py
Labels: update

#2335 Update URLs for test data for WRF to https
  easybuild/easyblocks/w/wps.py
Labels: bug fix

#2315 Fix for building GCC with --sysroot on ppc64le
  easybuild/easyblocks/g/gcc.py
Labels: bug fix

#2305 add custom easyblock to support installation of new Intel compilers (v2021.x, oneAPI)
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/intelbase.py
  easybuild/easyblocks/i/intel_compilers.py
  test/easyblocks/init_easyblocks.py
  test/easyblocks/module.py
Labels: enhancement, new

#2308 Make sure the installation of libiberty.a in the binutils easyblock goes into a populated directory
  easybuild/easyblocks/b/binutils.py
Labels: bug fix, change

#2322 Add sanity check commands to GCC (including LTO support)
  easybuild/easyblocks/g/gcc.py
Labels: enhancement

#2313 update impi easyblock for impi 2021.x (oneAPI)
  easybuild/easyblocks/i/impi.py
Labels: update

#2324 pass $CXXFLAGS to PDT's configure script via '-useropt'
  easybuild/easyblocks/p/pdt.py
Labels: bug fix

#2256 add foamMonitor to sanity checks of OpenFOAM
  easybuild/easyblocks/o/openfoam.py
Labels: enhancement

#2340 read MATLAB configuration file in binary mode to avoid UTF-8 encoding errors when using Python 3.6
  easybuild/easyblocks/m/matlab.py
Labels: bug fix

#2254 filter out user packages in LAMMPS easyblock if corresponding dependency isn't included + only set -DUSER-INTEL on x86_64 systems
  easybuild/easyblocks/l/lammps.py
Labels: bug fix, enhancement

#2201 run motorBike tutorial case for recent (community) OpenFOAM versions
  easybuild/easyblocks/o/openfoam.py
Labels: EESSI, enhancement

#2341 fix Boost sanity check on aarch64
  easybuild/easyblocks/b/boost.py
Labels: EESSI, bug fix

#2342 update release notes + bump version for EasyBuild v4.3.3
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: documentation, update

#2344 use 'main' rather than 'master' branch in test suite configuration
  .github/workflows/unit_tests.yml
  .travis.yml
Labels: change

#2345 sync with main branch + bump version to 4.3.4dev
  .github/workflows/unit_tests.yml
  .travis.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2346 make OpenCV easyblock aware of protobuf, libwebp and OpenEXR dependencies provided via EasyBuild
  easybuild/easyblocks/o/opencv.py
Labels: enhancement

#2348 update PETSc easyblock to take into account that ScaLAPACK installation may not have header files + fix building in parallel
  easybuild/easyblocks/p/petsc.py
Labels: bug fix

#2351 Disable CMake user package repository
  easybuild/easyblocks/generic/cmakemake.py
Labels: bug fix
