Repository easybuilders/easybuild-easyblocks, pull requests merged in 2021-12, with the labels that each got.

#2596 Set OpenMPI configuration for orca sanity check
  easybuild/easyblocks/o/orca.py
Labels: bug fix

#2630 avoid patching binary files + other enhancements for MUMmer easyblock
  easybuild/easyblocks/m/mummer.py
Labels: enhancement, bug fix

#2631 enable build-in-installdir mode in constructor of PETSc and SLEPc easyblocks
  easybuild/easyblocks/p/petsc.py
  easybuild/easyblocks/s/slepc.py
Labels: bug fix

#2619 add option to control MKL-DNN in jaxlib easyblock
  easybuild/easyblocks/j/jaxlib.py
Labels: enhancement

#2611 allow oversubscription in OpenMPI sanity check
  easybuild/easyblocks/o/openmpi.py
Labels: bug fix

#2616 set wm_* class variable in OpenFOAM easyblock when using --sanity-check-only
  easybuild/easyblocks/h/healpix.py
  easybuild/easyblocks/o/openfoam.py
  test/easyblocks/init_easyblocks.py
Labels: bug fix

#2617 add custom easyblock for Clang-AOMP
  easybuild/easyblocks/c/clang_aomp.py
Labels: new

#2633 add support for v3.4 in Eigen easyblock
  easybuild/easyblocks/e/eigen.py
Labels: update

#2634 skip netcdf4-python tests that require network connectivity
  easybuild/easyblocks/n/netcdf4_python.py
Labels: bug fix

#2632 prepare release notes for EasyBuild v4.5.1 + bump version to 4.5.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2635 release EasyBuild v4.5.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/c/clang_aomp.py
  easybuild/easyblocks/c/cp2k.py
  easybuild/easyblocks/e/eigen.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/rpm.py
  easybuild/easyblocks/h/healpix.py
  easybuild/easyblocks/i/inspector.py
  easybuild/easyblocks/j/jaxlib.py
  easybuild/easyblocks/m/mummer.py
  easybuild/easyblocks/n/netcdf4_python.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/o/orca.py
  easybuild/easyblocks/p/petsc.py
  easybuild/easyblocks/s/samtools.py
  easybuild/easyblocks/s/slepc.py
  easybuild/easyblocks/t/tbb.py
  setup.py
  test/easyblocks/init_easyblocks.py
Labels: update

#2636 sync with main + bump version to 4.5.2dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2639 add option to not copy the license file for Gurobi
  easybuild/easyblocks/g/gurobi.py
Labels: enhancement

#2641 fix license file when running with --module-only for Gurobi
  easybuild/easyblocks/g/gurobi.py
Labels: bug fix

#2640 fix shebang of scripts in Perl installation if installation prefix is too long
  easybuild/easyblocks/p/perl.py
Labels: bug fix, EESSI

#2637 use all available cores for running Perl test suite
  easybuild/easyblocks/p/perl.py
Labels: enhancement, performance

#2492 remove necessity for license for oneAPI versions (>= 2021.x) in itac easyblock
  easybuild/easyblocks/i/itac.py
Labels: update

#2643 update AOCC easyblock to support version 3.2.0
  easybuild/easyblocks/a/aocc.py
Labels: update

#2642 enhance IntelBase easyblock to avoid crash when $USER is not set
  easybuild/easyblocks/generic/intelbase.py
Labels: bug fix

#2644 don't grep for specific version in --version output of Intel compiler commands for versions 2022.x
  easybuild/easyblocks/i/intel_compilers.py
Labels: update

#2627 add CUDA support in SuiteSparse easyblock
  easybuild/easyblocks/s/suitesparse.py
Labels: enhancement
