Repository easybuilders/easybuild-easyblocks, pull requests merged in 2021-08, with the labels that each got.

#2527 Add support for imkl 2021.x in amber EasyBlock
  easybuild/easyblocks/a/amber.py
Labels: enhancement

#2528 Add support for imkl 2021.x in BerkeleyGW EasyBlock
  easybuild/easyblocks/b/berkeleygw.py
Labels: enhancement

#2530 Add support for imkl 2021.x in FreeFEM easyblock
  easybuild/easyblocks/f/freefem.py
Labels: enhancement

#2529 Add support for imkl 2021.x in CP2K easyblock
  easybuild/easyblocks/c/cp2k.py
Labels: enhancement

#2531 Add support for imkl 2021.x in GROMACS easyblock
  easybuild/easyblocks/g/gromacs.py
Labels: enhancement

#2532 Add support for imkl 2021.x in numexpr easyblock
  easybuild/easyblocks/n/numexpr.py
Labels: enhancement

#2534 add install_src option and enhance buildcmd option in PythonPackage easyblock
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#2537 set $I_MPI_ROOT correctly for 2021.x in impi easyblock
  easybuild/easyblocks/i/impi.py
Labels: bug fix

#2543 let Bundle easyblock pick up custom easyblock for components based on name if no easyblock is specified explicitly
  easybuild/easyblocks/generic/bundle.py
Labels: enhancement

#2535 Remove deprecated options from PythonPackage
  easybuild/easyblocks/generic/pythonpackage.py
Labels: code cleanup

#2547 correctly determine easyblock to use for Bundle components
  easybuild/easyblocks/generic/bundle.py
Labels: bug fix

#2544 fix motorBike test in sanity check for OpenFOAM 9
  easybuild/easyblocks/o/openfoam.py
Labels: update

#2550 Keep symlinks in cuDNN installations
  easybuild/easyblocks/c/cudnn.py
Labels: bug fix

#2487 add custom easyblock for CRISPR-DAV
  easybuild/easyblocks/c/crispr_dav.py
Labels: new

#2552 use ${BLAS,LAPACK}_SHARED_LIBS in GROMACS easyblock for FlexiBLAS-based toolchains
  easybuild/easyblocks/g/gromacs.py
Labels: bug fix

#2549 generate and install pkg-config files for OpenSSL wrapper
  easybuild/easyblocks/o/openssl_wrapper.py
Labels: enhancement

#2554 don't run "setup.py config" for numpy >= 1.21, since it's no longer supported
  easybuild/easyblocks/n/numpy.py
Labels: enhancement

#2556 copy the list to avoid changing the original lists in DEFAULT_TARGETS_MAP for Clang and LLVM
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/l/llvm.py
Labels: bug fix

#2513 Simplify Boost easyblock
  easybuild/easyblocks/b/boost.py
Labels: enhancement

#2558 wien2k: update to handle new intel versions, WIEN2k v21, Perl dependency and tuning of dimension parameters.
  easybuild/easyblocks/w/wien2k.py
Labels: bug fix, update

#2444 Enable make check and sanity check exec for OpenMPI
  easybuild/easyblocks/o/openmpi.py
Labels: enhancement
