Repository easybuilders/easybuild-easyblocks, pull requests merged in 2021-01, with the labels that each got.

#2297 update BerkeleyGW easyblock to support GCC 10 and fftlib
  easybuild/easyblocks/b/berkeleygw.py
Labels: enhancement, update

#2298 update quantumespresso easyblock to support GCC 10
  easybuild/easyblocks/q/quantumespresso.py
Labels: update

#2300 make builddeps a list of names in SLEPc easyblock
  easybuild/easyblocks/s/slepc.py
Labels: bug fix

#2299 fix logic w.r.t. enabling Python support in PETSc
  easybuild/easyblocks/p/petsc.py
Labels: bug fix

#2301 make builddeps a list of names in Trilinos easyblock
  easybuild/easyblocks/t/trilinos.py
Labels: bug fix

#2302 prefer default value for extra options in easyblock module-only tests
  test/easyblocks/module.py
Labels: enhancement

#2289 Set $PYTHONNOUSERSITE in PythonBundle.extensions_step
  easybuild/easyblocks/generic/pythonbundle.py
Labels: enhancement

#2291 Fix Boost sanity check on POWER
  easybuild/easyblocks/b/boost.py
Labels: bug fix

#2310 update Clang easyblock to add support for building extra tools + leveraging hwloc and Z3 as optional dependencies
  easybuild/easyblocks/c/clang.py
Labels: enhancement

#2282 enhance Amber easyblock to fix running of update_amber script when 'python' command is not available in OS
  easybuild/easyblocks/a/amber.py
Labels: bug fix

#2311 add check for accepted EULA in custom easyblock for NVHPC
  easybuild/easyblocks/n/nvhpc.py
Labels: enhancement

#2285 improve Bazel easyblock: add support for running tests, enable static linking, use build dir rather than tmpdir, verbose output
  easybuild/easyblocks/b/bazel.py
Labels: enhancement

#2319 Update quantumespresso to handle v6.7.
  easybuild/easyblocks/q/quantumespresso.py
Labels: update

#2323 Use library search paths of compiler for RPATH when building binutils with system compiler + enhance sanity check by running --version for binutils commands
  easybuild/easyblocks/b/binutils.py
Labels: bug fix
