Repository easybuilders/easybuild-easyblocks, pull requests merged in 2021-09, with the labels that each got.

#2536 reset runtest to None in CMakePythonPackage
  easybuild/easyblocks/generic/cmakepythonpackage.py
Labels: bug fix, code cleanup

#2510 add Ampere to known GPU architectures for Kokkos in LAMMPS easyblock
  easybuild/easyblocks/l/lammps.py
Labels: update

#2561 fix pathsep join bug that breaks installation of CUDA versions < 10.1 if $PERL5LIB is defined
  easybuild/easyblocks/c/cuda.py
Labels: bug fix

#2509 Clean up installation of Tkinter
  easybuild/easyblocks/p/python.py
  easybuild/easyblocks/t/tkinter.py
Labels: bug fix

#2448 Explicitely use only OpenBLAS for PyTorch if MKL is not used
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix

#2538 make sure AOCC commands like clang/flang pick up GCCcore as GCC toolchain
  easybuild/easyblocks/a/aocc.py
Labels: enhancement

#2560 add support for also installing Tosca component in ABAQUS
  easybuild/easyblocks/a/abaqus.py
Labels: enhancement

#2562 update ABAQUS easyblock to support installing of version 2021 with hot fixes
  easybuild/easyblocks/a/abaqus.py
Labels: enhancement

#2563 update sanity check in VTune easyblock for 2021.x versions
  easybuild/easyblocks/v/vtune.py
Labels: update

#2564 prepare release notes for EasyBuild v4.4.2 + bump version to 4.4.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2565 release EasyBuild v4.4.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/abaqus.py
  easybuild/easyblocks/a/amber.py
  easybuild/easyblocks/a/aocc.py
  easybuild/easyblocks/b/berkeleygw.py
  easybuild/easyblocks/b/boost.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/c/cp2k.py
  easybuild/easyblocks/c/crispr_dav.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/c/cudnn.py
  easybuild/easyblocks/e/esmf.py
  easybuild/easyblocks/f/freefem.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cmakepythonpackage.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/j/jaxlib.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/l/llvm.py
  easybuild/easyblocks/m/molpro.py
  easybuild/easyblocks/n/numexpr.py
  easybuild/easyblocks/n/numpy.py
  easybuild/easyblocks/o/opencv.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/o/openssl_wrapper.py
  easybuild/easyblocks/o/orca.py
  easybuild/easyblocks/p/python.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/r/repeatmodeler.py
  easybuild/easyblocks/t/tbb.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/tkinter.py
  easybuild/easyblocks/v/vtune.py
  easybuild/easyblocks/w/wien2k.py
  setup.py
Labels: update

#2567 sync with main + bump version to 4.4.3dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2568 unset $EASYBUILD_* environment variables when running sanity check in EasyBuildMeta easyblock + also unset $MODULES_LMCONFLICT to avoid conflict when loading EasyBuild module
  easybuild/easyblocks/e/easybuildmeta.py
Labels: bug fix

#2571 Let GROMACS runtime logs show EasyBuild was used
  easybuild/easyblocks/g/gromacs.py
Labels: enhancement

#2569 ensure that all ABAQUS components get installed for ABAQUS 2021.x (+ add support for enabling/disabling fe-safe)
  easybuild/easyblocks/a/abaqus.py
Labels: bug fix

#2572 adjust qa list in WIEN2k easyblock to handle new questions + fix sanity check for v21.1
  easybuild/easyblocks/w/wien2k.py
Labels: bug fix

#2576 fix subdir path in VTune easyblock for 2021.x versions + add sanity check command
  easybuild/easyblocks/v/vtune.py
Labels: bug fix

#2579 add support for specifying subdirectory for target installation directory in CMakMake
  easybuild/easyblocks/generic/cmakemake.py
Labels: enhancement

#2541 preparation for MotionCor2 1.4.4
  easybuild/easyblocks/m/motioncor2.py
Labels: enhancement, update
