Repository easybuilders/easybuild-easyblocks, pull requests merged in 2021-04, with the labels that each got.

#2377 Improve Python package version check and add unversioned_packages EC param
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#2326 set $R_LIBS_SITE rather than $R_LIBS when installing R packages
  easybuild/easyblocks/generic/rpackage.py
Labels: bug fix, change

#2363 also set $TORCH_CUDA_ARCH_LIST for PyTorch tests
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix

#2356 enhance cuDNN and CUDA easyblocks to support aarch64
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/c/cudnn.py
Labels: enhancement

#2371 enhance Hadoop easyblock to avoid copying same native library twice
  easybuild/easyblocks/h/hadoop.py
Labels: bug fix

#2373 Make the CUDA stub libs take preference over system libs when linking
  easybuild/easyblocks/c/cuda.py
Labels: bug fix

#2378 fix comment in NVHPC/AOCC easyblocks
  easybuild/easyblocks/a/aocc.py
  easybuild/easyblocks/n/nvhpc.py
Labels: bug fix, documentation

#2380 prepare release notes for EasyBuild v4.3.4 + bump version to 4.3.4
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2382 release EasyBuild v4.3.4
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/aocc.py
  easybuild/easyblocks/b/bwa.py
  easybuild/easyblocks/c/cp2k.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/c/cudnn.py
  easybuild/easyblocks/g/g2clib.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/generic/rpackage.py
  easybuild/easyblocks/h/hadoop.py
  easybuild/easyblocks/l/lapack.py
  easybuild/easyblocks/n/nvhpc.py
  easybuild/easyblocks/o/opencv.py
  easybuild/easyblocks/p/petsc.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/v/vmd.py
  easybuild/easyblocks/v/vtune.py
  easybuild/easyblocks/w/wps.py
  easybuild/easyblocks/w/wrf.py
Labels: update

#2383 sync with main branch + bump version to 4.3.5dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2381 add support for post install commands for python extensions
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#2384 update setup.py to indicate compatibility with Python 3.8 and 3.9
  setup.py
Labels: update

#2385 fix permission on MATLAB installer config file so it can be written to
  easybuild/easyblocks/m/matlab.py
Labels: bug fix

#2394 Update motioncor2 easyblock to handle new version and CUDAcore.
  easybuild/easyblocks/m/motioncor2.py
Labels: update

#2390 Add option to disable connecting to PyPi from pip
  easybuild/easyblocks/generic/pythonpackage.py
Labels: change, enhancement

#2395 Updated numpy easyblock to use read_file for patch.
  easybuild/easyblocks/n/numpy.py
Labels: bug fix

#2405 Replace hardcoded '2021.1.1' with 'self.version' in impi easyblock
  easybuild/easyblocks/i/impi.py
Labels: bug fix

#2406 Use on_error rather than deprecated log_error named argument for which function
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/t/tensorflow.py
Labels: change

#2366 Don't unpack whl files by default in generic PythonPackage easyblock
  easybuild/easyblocks/generic/pythonpackage.py
Labels: change, enhancement

#2403 Make it possible to force disabling kernel features in Qt easyblock
  easybuild/easyblocks/q/qt.py
Labels: EESSI

#2391 fix installopts before installing the extension in GROMACS easyblock
  easybuild/easyblocks/g/gromacs.py
Labels: bug fix
