Repository easybuilders/easybuild-easyblocks, pull requests merged in 2021-07, with the labels that each got.

#2485 change Bundle easyblock to also collect altroot and altversion in the module step so they are set when running --module-only
  easybuild/easyblocks/generic/bundle.py
Labels: bug fix

#2500 Rework the dependency handling of OpenMPI
  easybuild/easyblocks/o/openmpi.py
Labels: bug fix, enhancement

#2501 correctly check whether --with-ucx is used as OpenMPI configure option (taking into account --with-ucx=no)
  easybuild/easyblocks/o/openmpi.py
Labels: bug fix

#2457 Fix CPU-only runtime for dpcpp-generated executables in custom easyblock for intel-compilers
  easybuild/easyblocks/i/intel_compilers.py
Labels: bug fix

#2502 prepare release notes for EasyBuild v4.4.1 + bump version to 4.4.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2503 release EasyBuild v4.4.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/amber.py
  easybuild/easyblocks/a/aomp.py
  easybuild/easyblocks/b/boost.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/f/fftw.py
  easybuild/easyblocks/f/freefem.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/configuremake.py
  easybuild/easyblocks/h/hypre.py
  easybuild/easyblocks/i/intel_compilers.py
  easybuild/easyblocks/j/java.py
  easybuild/easyblocks/n/nccl.py
  easybuild/easyblocks/n/nvhpc.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/o/openssl_wrapper.py
  easybuild/easyblocks/p/perl.py
  easybuild/easyblocks/p/python.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/torchvision.py
  easybuild/easyblocks/u/ucx_plugins.py
  easybuild/easyblocks/v/vep.py
  easybuild/easyblocks/x/xalt.py
  easybuild/easyblocks/x/xmipp.py
  test/easyblocks/module.py
Labels: update

#2505 sync with main + bump version to 4.4.2dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2507 remove Python 2.6 from list of supported Python versions in setup.py
  setup.py
Labels: bug fix

#2499 fixed sanity check for later versions of molpro
  easybuild/easyblocks/m/molpro.py
Labels: update

#2512 update sanity check in ESMF easyblock to take into account new binary names from version 8.1.0 onwards
  easybuild/easyblocks/e/esmf.py
Labels: update

#2520 Use correct GTK+ for OpenCV
  easybuild/easyblocks/o/opencv.py
Labels: bug fix

#2504 add new easyblock for ORCA
  easybuild/easyblocks/o/orca.py
Labels: new

#2519 Use report_test_failure in TF
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#2511 Remove redundant CPATH entry of tbb modules
  easybuild/easyblocks/t/tbb.py
Labels: bug fix

#2516 Honor --ignore-test-failure in PythonPackage
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#2522 Fix sanity-check and debug builds of TensorFlow
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix, enhancement

#2524 Fix missed renaming l->x
  easybuild/easyblocks/__init__.py
Labels: bug fix
