Repository easybuilders/easybuild-easyblocks, pull requests merged in 2021-06, with the labels that each got.

#2450 Exclude bottleneck tests in PyTorch
  easybuild/easyblocks/p/pytorch.py
Labels: enhancement

#2451 prepare release notes for EasyBuild v4.4.0 + bump version to 4.4.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2452 release EasyBuild v4.4.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/b/boost.py
  easybuild/easyblocks/b/bwa.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/c/cryptography.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/d/dm_reverb.py
  easybuild/easyblocks/f/fftw.py
  easybuild/easyblocks/f/flexiblas.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/g/gurobi.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/mesonninja.py
  easybuild/easyblocks/generic/modulerc.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/i/imkl.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/m/matlab.py
  easybuild/easyblocks/m/motioncor2.py
  easybuild/easyblocks/n/numpy.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/openssl_wrapper.py
  easybuild/easyblocks/p/python.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/q/qt.py
  easybuild/easyblocks/s/scalapack.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/tkinter.py
  setup.py
  test/easyblocks/init_easyblocks.py
  test/easyblocks/module.py
Labels: update

#2455 sync with main + bump version to 4.4.1dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2454 enhance sanity check for Clang to verify if CUDA offload library was produced
  easybuild/easyblocks/c/clang.py
Labels: bug fix

#2453 only use siterc fix for NVHPC < 21.3
  easybuild/easyblocks/n/nvhpc.py
Labels: bug fix

#1969 add custom easyblock for FreeFEM
  easybuild/easyblocks/f/freefem.py
Labels: new

#2337 new easyblock for NCCL (built from source)
  easybuild/easyblocks/n/nccl.py
Labels: new

#2435 Add AOMP EasyBlock support
  easybuild/easyblocks/a/aomp.py
Labels: new

#2459 Always add add distinct_host_configuration=false to TensorFlow compilation
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix, change

#2462 add missing license header to AOMP easyblock + use filetools functions
  easybuild/easyblocks/a/aomp.py
Labels: code cleanup

#2458 Enhance sitecfg to support overriding core Python packages
  easybuild/easyblocks/p/python.py
Labels: change, enhancement

#2467 new easyblock for torchvision
  easybuild/easyblocks/t/torchvision.py
Labels: new

#2464 add sanity_check_step for Aomp easyblock
  easybuild/easyblocks/a/aomp.py
Labels: enhancement

#2449 enhance ConfigureMake generic easyblock to add support for building multiple build targets
  easybuild/easyblocks/generic/configuremake.py
Labels: enhancement

#2463 add file prefix option to XALT easyblock
  easybuild/easyblocks/x/xalt.py
Labels: enhancement

#2468 disable installation of bundled BioPerl and HTSLib if they are dependencies of VEP
  easybuild/easyblocks/v/vep.py
Labels: bug fix

#2474 Adjust perl.py to only check for a "man" directory if groff is a dependency.
  easybuild/easyblocks/p/perl.py
Labels: enhancement

#2445 Add CMake support for Amber 20
  easybuild/easyblocks/a/amber.py
Labels: enhancement, update

#2480 obtain build_targets value via self.cfg.get in ConfigureMake easyblock
  easybuild/easyblocks/generic/configuremake.py
Labels: bug fix

#2479 rename build_targets to build_cmd_targets in ConfigureMake as this clashes with the use in the Clang and LLVM easyblocks
  easybuild/easyblocks/generic/configuremake.py
Labels: bug fix

#2477 Enhance intel_compiler easyblock to inlude multipath include dir in $CPATH. See #1237 for original PR.
  easybuild/easyblocks/i/intel_compilers.py
Labels: bug fix

#2475 Support arbitrary version strings in OpenSSL wrapper and add minimum_openssl_version option
  easybuild/easyblocks/o/openssl_wrapper.py
Labels: enhancement

#2486 update Xmipp easyblock for new version (v3.20.07)
  easybuild/easyblocks/x/xmipp.py
Labels: update

#2472 enhance Java easyblock to define %(jdkarch)s template
  easybuild/easyblocks/j/java.py
Labels: enhancement

#2482 enhance Hypre easyblock to enable CUDA support
  easybuild/easyblocks/h/hypre.py
Labels: enhancement

#2469 don't use list value for command to detect installed Python packages in TensorFlow easyblock
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#2491 add custom easyblock for building UCX plugins
  easybuild/easyblocks/u/ucx_plugins.py
  test/easyblocks/module.py
Labels: new

#2489 always strip output from gcc -print-multiarch
  easybuild/easyblocks/i/intel_compilers.py
Labels: bug fix

#2490 allow disabling of tests if using MPI in FFTW easyblock
  easybuild/easyblocks/f/fftw.py
Labels: enhancement

#2493 Use PYPI_SOURCE as the default for source_urls of extensions of Python easyconfigs
  easybuild/easyblocks/p/python.py
Labels: enhancement

#2494 Don't overwrite all of exts_default_options in TensorFlow easyblock
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#2498 make sure that system GCC provides LTO support, and disable LTO when building MPFR if not
  easybuild/easyblocks/g/gcc.py
Labels: EESSI, bug fix

#2456 update custom easyblock for Boost to always build single and multi threaded versions
  easybuild/easyblocks/b/boost.py
Labels: bug fix, enhancement

#2461 update CMakeMake to handle old and new Boost/Boost.Python builds using custom easyblock for Boost
  easybuild/easyblocks/generic/cmakemake.py
Labels: enhancement

#2483 Enhance sitecustomize.py script installed by Python easyblock to fix support for virtualenv
  easybuild/easyblocks/p/python.py
Labels: bug fix
