Repository easybuilders/easybuild-easyblocks, pull requests merged in 2022-09, with the labels that each got.

#2772 use det_cmake_version function to determine CMake version in CMakeMake generic easyblock
  easybuild/easyblocks/generic/cmakemake.py
  test/easyblocks/easyblock_specific.py
Labels: enhancement, bug fix

#2783 fix version check for NVPTX library in sanity check of Clang easyblock
  easybuild/easyblocks/c/clang.py
Labels: bug fix

#2784 prepare release notes for EasyBuild v4.6.1 + bump version to 4.6.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2785 release EasyBuild 4.6.1
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/amber.py
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/f/fftwmpi.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/l/libqglviewer.py
  easybuild/easyblocks/n/nvhpc.py
  easybuild/easyblocks/p/pytorch.py
  test/easyblocks/easyblock_specific.py
Labels: update

#2790 handle problems copying symlink that points to CUDA folder that is not created for non CUDA builds of SuiteSparse
  easybuild/easyblocks/s/suitesparse.py
Labels: bug fix

#2789 added support for ESMPy in ESMF
  easybuild/easyblocks/e/esmf.py
Labels: enhancement

#2792 Remove docs and java and add Rocky support for ABAQUS
  easybuild/easyblocks/a/abaqus.py
Labels: bug fix
