Repository easybuilders/easybuild-easyblocks, pull requests merged in 2022-11, with the labels that each got.

#2799 fix installing of Clang with RPATH linking
  easybuild/easyblocks/c/clang.py
Labels: bug fix

#2796 update PETSc easyblock for newer versions
  easybuild/easyblocks/p/petsc.py
Labels: update

#2680 add fix_shebang to install_step of PythonPackage easyblock so that we can fix shebangs when installing extensions
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#2825 enable building of static libraries for libxml2 >= 2.10
  easybuild/easyblocks/l/libxml2.py
Labels: update

#2827 use new EasyBuild logo in README
  README.rst
Labels: update, documentation

#2816 add generic JuliaPackage easyblock
  easybuild/easyblocks/generic/juliapackage.py
  test/easyblocks/module.py
Labels: new

#2821 Add extra option for disabling LAPACK in ESMF
  easybuild/easyblocks/e/esmf.py
Labels: enhancement

#2831 update xmipp.py to handle effects of CUDA at SYSTEM level and newer CUDA version requirements for stdc++
  easybuild/easyblocks/x/xmipp.py
Labels: enhancement

#2800 Added support clang 14+ new directory structure
  easybuild/easyblocks/c/clang.py
Labels: update

#2806 create $XDG_CACHE_HOME for PyTorch tests
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix

#2832 update LLVM easyblock to put 'cmake' symlink in place so separate CMake modules requires for LLVM 15+ can be found
  easybuild/easyblocks/l/llvm.py
Labels: update

#2833 fix docstring of PythonBundle generic easyblock
  easybuild/easyblocks/generic/pythonbundle.py
Labels: bug fix, documentation

#2830 add generic JuliaBundle easyblock
  easybuild/easyblocks/generic/juliabundle.py
  test/easyblocks/module.py
Labels: new

#2835 Cancel GithubAction runs for outdated commits
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
Labels: enhancement

#2834 Fix counting of failures in PyTorch tests
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix, code cleanup

#2840 Fix Python 2.7 compatibility of PyTorch easyblock
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix
