Repository easybuilders/easybuild-easyblocks, pull requests merged in 2022-06, with the labels that each got.

#2729 fix sanity checks for Clang 12+13 when built with NVPTX support
  easybuild/easyblocks/c/clang.py
Labels: bug fix

#2727 enhance MrBayes easyblock with custom sanity check command
  easybuild/easyblocks/m/mrbayes.py
Labels: enhancement

#2728 Change in cudnnarch string templates used to compose source tarball names from cuDNN 8.3.3 onwards
  easybuild/easyblocks/c/cudnn.py
Labels: enhancement

#2724 add custom easyblock for FFTW.MPI + modify FFTW's sanity check step to allow checking only for MPI parts of FFTW installation
  easybuild/easyblocks/f/fftw.py
  easybuild/easyblocks/f/fftwmpi.py
  test/easyblocks/module.py
Labels: new

#2735 also symlink cert.pem in from-source OpenSSL installation (if it exists) + add sanity check command to OpenSSL wrapper easyblock to verify that system certificates are available to OpenSSL
  easybuild/easyblocks/o/openssl.py
  easybuild/easyblocks/o/openssl_wrapper.py
Labels: enhancement, bug fix

#2709 update sanity check in OpenMPI easyblock to support OpenMPI v5.0.0
  easybuild/easyblocks/o/openmpi.py
Labels: update

#2736 ignore exit code of pkg-config command in OpenSSL wrapper easyblock, since with pkgconf they exit with a non-zero exit code if the OS package is not installed
  easybuild/easyblocks/o/openssl_wrapper.py
Labels: enhancement

#2737 also run tests if a custom test_cmd has been supplied
  easybuild/easyblocks/generic/configuremake.py
Labels: enhancement

#2739 prepare release notes for EasyBuild v4.5.5 + bump version to 4.5.5
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2740 release EasyBuild v4.5.5
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/abaqus.py
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/c/cudnn.py
  easybuild/easyblocks/f/fftw.py
  easybuild/easyblocks/f/fftwmpi.py
  easybuild/easyblocks/f/freesurfer.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/generic/configuremake.py
  easybuild/easyblocks/l/llvm.py
  easybuild/easyblocks/m/mesa.py
  easybuild/easyblocks/m/mrbayes.py
  easybuild/easyblocks/n/neuron.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/o/openssl.py
  easybuild/easyblocks/o/openssl_wrapper.py
  easybuild/easyblocks/r/r.py
  easybuild/easyblocks/s/superlu.py
  easybuild/easyblocks/t/tensorflow.py
  test/easyblocks/module.py
Labels: update

#2741 sync with main + bump version to 4.5.6dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2743 make VEP easyblock compatible with --sanity-check-only
  easybuild/easyblocks/v/vep.py
Labels: bug fix

#2744 update Rosetta easyblock to take into account that $LD_LIBRARY_PATH, $CPATH, $PATH may not be defined
  easybuild/easyblocks/r/rosetta.py
Labels: bug fix

#1613 add custom easyblock for STAR-CCM+
  easybuild/easyblocks/s/star_ccm.py
Labels: new

#2747 Allow pybind11 to be installed as an extension
  easybuild/easyblocks/p/pybind11.py
Labels: bug fix

#2748 make sure that CMakeMakeCp uses correct build dir
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/cmakemakecp.py
Labels: bug fix

#2738 enable building of shared library for Libint 2.7+
  easybuild/easyblocks/l/libint.py
Labels: enhancement

#2752 add more logging to install_pc_files method of OpenSSL wrapper easyblock
  easybuild/easyblocks/o/openssl_wrapper.py
Labels: enhancement

#2690 update Siesta EasyBlock to support GCC 10+ by adding -fallow-argument-mismatch Fortran compiler option
  easybuild/easyblocks/s/siesta.py
Labels: enhancement
