Repository easybuilders/easybuild-easyblocks, pull requests merged in 2022-03, with the labels that each got.

#2688 enhance Tarball easyblock to support using it for installing extensions
  easybuild/easyblocks/generic/tarball.py
Labels: enhancement

#2691 enhance Gurobi easyblock to also update $MATLABPATH
  easybuild/easyblocks/g/gurobi.py
Labels: enhancement

#2692 force use of bash for Anaconda install script
  easybuild/easyblocks/a/anaconda.py
Labels: bug fix

#2689 update wxPython easyblock to support wxPython v4.1
  easybuild/easyblocks/w/wxpython.py
Labels: enhancement

#2687 avoid dependency on 'which' command in sanity check for Python, use 'command -v' instead
  easybuild/easyblocks/p/python.py
Labels: enhancement

#2683 enable system SSL certificates in OpenSSL installations
  easybuild/easyblocks/o/openssl.py
  easybuild/easyblocks/o/openssl_wrapper.py
Labels: enhancement

#2696 Add guess for MANPATH for intel-compilers.
  easybuild/easyblocks/i/intel_compilers.py
Labels: bug fix

#2701 also consider $MKLROOT/lib/pkgconfig for $PKG_CONFIG_PATH for imkl
  easybuild/easyblocks/i/imkl.py
Labels: bug fix

#2702 close log after installing Bundle component
  easybuild/easyblocks/generic/bundle.py
Labels: bug fix

#2338 set $NINJAFLAGS to make sure Ninja doesn't use all visible cores when building Qt5
  easybuild/easyblocks/q/qt.py
Labels: bug fix

#2698 Change permissions of the Java builddir to avoid permission denied error
  easybuild/easyblocks/j/java.py
Labels: bug fix

#2694 build single-file shared libraries for imkl so it can be used as FlexiBLAS backend via $FLEXIBLAS_LIBRARY_PATH
  easybuild/easyblocks/f/flexiblas.py
  easybuild/easyblocks/i/imkl.py
Labels: enhancement

#2703 replace hardcoded /tmp to make sure that Bazel build respects $TMPDIR
  easybuild/easyblocks/b/bazel.py
Labels: bug fix

#2704 prepare release notes for EasyBuild v4.5.4 + bump version to 4.5.4
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2707 sync with main + bump version to 4.5.5dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update
