Repository easybuilders/easybuild-easyblocks, pull requests merged in 2022-10, with the labels that each got.

#2766 update OpenFOAM easyblock to support OpenFOAM 10 + clean up variant/version checks
  easybuild/easyblocks/o/openfoam.py
Labels: update, code cleanup

#2798 handle iterative builds with MakeCP EasyBlock
  easybuild/easyblocks/generic/makecp.py
Labels: bug fix

#2797 Make the test output from PythonPackage less verbose
  easybuild/easyblocks/generic/pythonpackage.py
Labels: change

#2794 Correctly count the number of failing tests (not failing test suites) in PyTorch builds
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix

#2764 Add easyblock for CUDA compatibility libraries
  easybuild/easyblocks/c/cudacompat.py
Labels: new

#2803 correctly count errors/failures in PyTorch test summary
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix

#2805 enhance EasyBuildMeta easyblock: auto-enable installing with pip + fix setup.py of easyconfigs package so installation with setuptools >= 61.0 works
  easybuild/easyblocks/e/easybuildmeta.py
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix, EESSI

#2811 add sanity check commands for netCDF
  easybuild/easyblocks/n/netcdf.py
Labels: enhancement

#2810 make numexpr easyblock aware of toolchain with GCC + imkl
  easybuild/easyblocks/n/numexpr.py
Labels: enhancement

#2812 prepare release notes for EasyBuild v4.6.2 + bump version to 4.6.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2813 release EasyBuild 4.6.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/abaqus.py
  easybuild/easyblocks/c/cudacompat.py
  easybuild/easyblocks/d/dm_reverb.py
  easybuild/easyblocks/e/easybuildmeta.py
  easybuild/easyblocks/e/esmf.py
  easybuild/easyblocks/generic/makecp.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/m/mamba.py
  easybuild/easyblocks/n/netcdf.py
  easybuild/easyblocks/n/numexpr.py
  easybuild/easyblocks/o/openblas.py
  easybuild/easyblocks/o/opencv.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/s/suitesparse.py
  easybuild/easyblocks/t/tensorrt.py
Labels: update

#2814 sync with main + bump version to 4.6.3dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2575 enhance TensorFlow easyblock to take into account provided OpenSSL dependency
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#2809 update Xmipp easyblock: versions >= 3.20.07 use `noAsk` option to configure
  easybuild/easyblocks/x/xmipp.py
Labels: update

#2818 opencv v4, add include/opencv4 to CPATH
  easybuild/easyblocks/o/opencv.py
Labels: bug fix
