Repository easybuilders/easybuild-easyblocks, pull requests merged in 2022-01, with the labels that each got.

#2553 convert version numbers to stricly numerical in Siesta easyblock
  easybuild/easyblocks/s/siesta.py
Labels: enhancement, python3

#2645 fix quotes in definition of default platform macro and enhance sanity check in GATE easyblock
  easybuild/easyblocks/g/gate.py
Labels: bug fix

#2648 avoid excessively long shebang line in compile script for WRF
  easybuild/easyblocks/w/wrf.py
Labels: bug fix, EESSI

#2653 add sanity check command for Bazel
  easybuild/easyblocks/b/bazel.py
Labels: enhancement

#2651 fix checking of Intel Fortran compiler version in CP2K easyblock for recent toolchains
  easybuild/easyblocks/c/cp2k.py
Labels: bug fix

#2649 Add support for enabling sanity checks for specific components in the Bundle easyblock
  easybuild/easyblocks/generic/bundle.py
Labels: enhancement

#2658 add util subdirectory to $PATH for WPS
  easybuild/easyblocks/w/wps.py
Labels: enhancement

#2652 update Mathematica easyblock for version 13
  easybuild/easyblocks/m/mathematica.py
Labels: update

#2654 update NAMD easyblock to allow non-system csh
  easybuild/easyblocks/n/namd.py
Labels: enhancement

#2660 prepare release notes for EasyBuild v4.5.2 + bump version to 4.5.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2661 release EasyBuild v4.5.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/aocc.py
  easybuild/easyblocks/b/bazel.py
  easybuild/easyblocks/c/cp2k.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/g/gate.py
  easybuild/easyblocks/g/gurobi.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/intelbase.py
  easybuild/easyblocks/i/intel_compilers.py
  easybuild/easyblocks/i/itac.py
  easybuild/easyblocks/l/libint.py
  easybuild/easyblocks/m/mathematica.py
  easybuild/easyblocks/n/namd.py
  easybuild/easyblocks/p/perl.py
  easybuild/easyblocks/s/siesta.py
  easybuild/easyblocks/s/suitesparse.py
  easybuild/easyblocks/w/wps.py
  easybuild/easyblocks/w/wrf.py
Labels: update

#2663 sync with main + bump version to 4.5.3dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2664 also run easyblocks test suite with Python 3.8-3.10 + consistently us…
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
  test/easyblocks/module.py
Labels: enhancement, bug fix, tests
