Repository easybuilders/easybuild-easyblocks, pull requests merged in 2022-08, with the labels that each got.

#2730 update libQGLViewer easyblock to take into account changes in the shared library names depending on Qt versions they are compiled with
  easybuild/easyblocks/l/libqglviewer.py
Labels: update

#2770 enhance PythonPackage easyblock to make sure all test command output makes it to the EasyBuild log, also when return_output_ec=True
  easybuild/easyblocks/generic/pythonpackage.py
Labels: enhancement

#2768 enhance PyTorch easyblock to also capture tests failing with signal
  easybuild/easyblocks/p/pytorch.py
Labels: enhancement

#2776 Set NVHPC_CUDA_HOME for NVHPC 22.7+
  easybuild/easyblocks/n/nvhpc.py
Labels: enhancement

#2771 fix FFTW.MPI on lib64 distros (such as SUSE) to prevents not found paths
  easybuild/easyblocks/f/fftwmpi.py
Labels: bug fix

#2779 update CI workflows to use Ubuntu 20.04 (since Ubuntu 18.04 is deprecated)
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
Labels: update, change, tests

#2720 make Amber easyblock aware of FlexiBLAS
  easybuild/easyblocks/a/amber.py
Labels: enhancement, bug fix

#2767 enhance NVHPC easyblock to avoid superfluous warning
  easybuild/easyblocks/n/nvhpc.py
Labels: enhancement

#2765 make `$LD_LIBRARY_PATH` detection more robust for LAMMPS
  easybuild/easyblocks/l/lammps.py
Labels: enhancement

#2781 tweak Amber(Tools) easyblock to run tests from top-level directory
  easybuild/easyblocks/a/amber.py
Labels: bug fix

#2780 don't enable building of ld.gold when installing binutils on a RISC-V system + don't configure GCC to use gold as default linker on a RISC-V system
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/g/gcc.py
Labels: bug fix
