Repository easybuilders/easybuild-easyblocks, pull requests merged in 2022-02, with the labels that each got.

#2667 specify easybuild.io as EasyBuild homepage in setup.py
  setup.py
Labels: bug fix, documentation

#2670 remove vulnerable binaries from sanity check of HDF5, no longer installed by default with HDF5 1.10.8
  easybuild/easyblocks/h/hdf5.py
Labels: update

#2669 update sanity check in CUDA EasyBlock: CUDA 11.6 no longer includes samples
  easybuild/easyblocks/c/cuda.py
Labels: update

#2666 add support to NAMD easyblock to opt out of building with CUDA support even if CUDA is included as dependency
  easybuild/easyblocks/n/namd.py
Labels: enhancement

#2655 set CUDA target architecture(s) for GROMACS based on cuda_cc_semicolon_sep template value
  easybuild/easyblocks/g/gromacs.py
Labels: enhancement

#2668 add custom easyblock for reticulate R package
  easybuild/easyblocks/r/reticulate.py
Labels: new

#2676 release EasyBuild v4.5.3
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/h/hdf5.py
  easybuild/easyblocks/n/namd.py
  easybuild/easyblocks/r/reticulate.py
  setup.py
  test/easyblocks/module.py
Labels: update

#2677 sync with main + bump version to 4.5.4dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2331 added regex to replace /lib/cpp with cpp in OpenFOAM's wmake rules file
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix

#2662 Update Siesta EasyBlock to use serial FFTW
  easybuild/easyblocks/s/siesta.py
Labels: bug fix

#2678 fix support for imkl for numexpr 2.8.0+ in numexpr easyblock
  easybuild/easyblocks/n/numexpr.py
Labels: bug fix

#2679 minor code cleanup in numexpr easyblock
  easybuild/easyblocks/n/numexpr.py
Labels: code cleanup

#2682 Make sure TensorFlow doesn't see the nvptx-none dir when searching for gcc include dir
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#2681 update Clang-AOMP easyblock to add support for ROCm v5.0
  easybuild/easyblocks/c/clang_aomp.py
Labels: enhancement

#2685 Add openmp, parallel build support for MRtrix easyblock
  easybuild/easyblocks/m/mrtrix.py
Labels: enhancement
