Repository easybuilders/easybuild-easyblocks, pull requests merged in 2022-07, with the labels that each got.

#2758 disable altivec when building FFTW versions < 3.4 with single-precision with GCC on POWER
  easybuild/easyblocks/f/fftw.py
Labels: change

#2757 add Abseil system dependency for TensorFlow 2.9+
  easybuild/easyblocks/t/tensorflow.py
Labels: enhancement

#2760 prepare release notes for EasyBuild v4.6.0 + bump version to 4.6.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2761 release EasyBuild v4.6.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/b/bazel.py
  easybuild/easyblocks/f/fftw.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/cmakemakecp.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/l/libint.py
  easybuild/easyblocks/o/openssl_wrapper.py
  easybuild/easyblocks/p/pybind11.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/r/rosetta.py
  easybuild/easyblocks/s/siesta.py
  easybuild/easyblocks/s/star_ccm.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/v/vep.py
  easybuild/easyblocks/w/wps.py
Labels: update

#2762 sync with main + bump version to 4.6.1dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2749 improve PLUMED detection in GROMACS easyblock
  easybuild/easyblocks/g/gromacs.py
Labels: enhancement

#2763 PyTorch: Disable breakpad on PPC
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix

#2213 Update LAMMPS easyblock for LAMMPS/23Jun22
  easybuild/easyblocks/l/lammps.py
Labels: update

#2514 Reduce the number of command line args for CMake configure
  easybuild/easyblocks/generic/cmakemake.py
Labels: enhancement
