Repository easybuilders/easybuild-easyblocks, pull requests merged in 2023-03, with the labels that each got.

#2868 modify logic in QScintilla easyblock to find the PyQt5 sipdir in more places
  easybuild/easyblocks/q/qscintilla.py
Labels: enhancement

#2879 add deprecation notice to RPackage extensions with relative paths in start_dir
  easybuild/easyblocks/generic/rpackage.py
Labels: change

#2900 update Trilinos easyblock to allow disabling of building tests and forward deps + support Trilinos v13.x
  easybuild/easyblocks/t/trilinos.py
Labels: enhancement, update

#2883 avoid crash in test step of PyTorch easyblock if runtest is not a command
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix

#2874 Show template values of exts_default_options in PythonBundle
  easybuild/easyblocks/generic/pythonbundle.py
Labels: bug fix

#2903 update scipy easyblock to copy PKG-INFO to scipy-<version>.egg-info when installing with Meson/Ninja + enhance add sanity check command using 'pip list'
  easybuild/easyblocks/s/scipy.py
Labels: bug fix

#2882 handle templating correctly in CMakeMake when playing with configopts
  easybuild/easyblocks/generic/cmakemake.py
Labels: bug fix

#2876 Fix missing initialization of CMakeMake in CMakePythonPackage
  easybuild/easyblocks/generic/cmakepythonpackage.py
Labels: bug fix

#2904 enhance Python easyblock to create non-versioned symlink for python-config + check for bin/python and bin/python-config in sanity check
  easybuild/easyblocks/p/python.py
Labels: enhancement

#2854 fix TensorFlow easyblock for new versions of Bazel & TensorFlow
  easybuild/easyblocks/t/tensorflow.py
Labels: update

#2907 prepare release notes for EasyBuild v4.7.1 + bump version to 4.7.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2908 release EasyBuild v4.7.1
  .github/workflows/linting.yml
  .github/workflows/unit_tests.yml
  README.rst
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/e/easybuildmeta.py
  easybuild/easyblocks/e/elpa.py
  easybuild/easyblocks/f/flexiblas.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/cmakepythonpackage.py
  easybuild/easyblocks/generic/gopackage.py
  easybuild/easyblocks/generic/juliapackage.py
  easybuild/easyblocks/generic/mesonninja.py
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/generic/rpackage.py
  easybuild/easyblocks/m/maple.py
  easybuild/easyblocks/m/mathematica.py
  easybuild/easyblocks/n/namd.py
  easybuild/easyblocks/n/netcdf.py
  easybuild/easyblocks/n/numexpr.py
  easybuild/easyblocks/n/nvhpc.py
  easybuild/easyblocks/p/pybind11.py
  easybuild/easyblocks/p/python.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/q/qscintilla.py
  easybuild/easyblocks/s/scipy.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/trilinos.py
Labels: update

#2911 sync with main + bump version to 4.7.2dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2914 use string '0' to avoid problems when opensll version is not determined
  easybuild/easyblocks/o/openssl_wrapper.py
Labels: bug fix

#2906 inform users that gpu package (instead of kokkos) is used for LAMMPS
  easybuild/easyblocks/l/lammps.py
Labels: enhancement
