Repository easybuilders/easybuild-easyblocks, pull requests merged in 2023-12, with the labels that each got.

#3052 update Ferret easyblock to be compatible with v7.6.0
  easybuild/easyblocks/f/ferret.py
Labels: enhancement

#3049 fix+enhance NWChem easyblock
  easybuild/easyblocks/n/nwchem.py
Labels: enhancement, bug fix

#3054 Add binutils symlinks when building TensorFlow with --rpath
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#3039 update custom easyblock for Intel MPI easyblock for v2021.11
  easybuild/easyblocks/i/impi.py
Labels: update

#2964 add generic `CargoPythonBundle` easyblock
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cargopythonbundle.py
  test/easyblocks/module.py
Labels: new

#3058 take into account that binutils might be a filtered dependency for TensorFlow
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix

#3042 update custom easyblock for Intel MKL for v2024.x
  easybuild/easyblocks/generic/intelbase.py
  easybuild/easyblocks/i/imkl.py
Labels: update

#3057 fix `det_pylibdir` provided by `PythonPackage` easyblock for Python 3.12+
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#3059 fix nvptx sanity check for Clang >= 14.x
  easybuild/easyblocks/c/clang.py
Labels: bug fix

#3031 add custom easyconfig parameter `cmake_options` to SuiteSparse easyblock
  easybuild/easyblocks/s/suitesparse.py
Labels: enhancement

#3044 also consider `$EB_COMSOL_LICENSE_FILE` environment variable in custom easyblock for COMSOL
  easybuild/easyblocks/c/comsol.py
Labels: change

#3056 fix specifying path to SuiteSparse header files and libraries in numpy, Trilinos, PETSc easyblocks
  easybuild/easyblocks/n/numpy.py
  easybuild/easyblocks/p/petsc.py
  easybuild/easyblocks/t/trilinos.py
Labels: bug fix

#3060 prepare release notes for EasyBuild v4.9.0 + bump version to 4.9.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update, documentation

#3062 sync with main + bump version to 4.9.1dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update
