Repository easybuilders/easybuild-easyblocks, pull requests merged in 2023-06, with the labels that each got.

#2943 stop running tests with Python 2.7 since it is no longer supported in GitHub Actions
  .github/workflows/unit_tests.yml
Labels: bug fix, change, tests

#2944 `make shared` is necessary and sufficient with 0.3.23 + xianyi/OpenBLAS#3983
  easybuild/easyblocks/o/openblas.py
Labels: bug fix

#2941 add support for NVIDIA Hopper CC 9.0 in LAMMPS
  easybuild/easyblocks/l/lammps.py
Labels: enhancement

#2947 improve handling of `optarch` in `Cargo` easyblock
  easybuild/easyblocks/generic/cargo.py
Labels: bug fix

#2951 reset modules loaded by PythonPackage to let ExtensionEasyBlock handle `multi_deps` correctly
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#2945 add `PerlBundle` generic easyblock for installing a bundle of Perl modules
  easybuild/easyblocks/generic/perlbundle.py
Labels: new

#2953 add support for `install_cmds` in `Binary` easyblock
  easybuild/easyblocks/generic/binary.py
Labels: enhancement

#2952 add custom easyblock for Rust
  easybuild/easyblocks/r/rust.py
Labels: new
