Repository easybuilders/easybuild-easyblocks, pull requests merged in 2023-02, with the labels that each got.

#2877 fix error when failing PIP version check during PythonPackage sanity check
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#2889 Use older `ncgen -H` for older netCDF
  easybuild/easyblocks/n/netcdf.py
Labels: bug fix

#2886 fix check configure option in FlexiBLAS easyblock
  easybuild/easyblocks/f/flexiblas.py
Labels: bug fix

#2878 use -x option for "go install" in GoPackage generic easyblock
  easybuild/easyblocks/generic/gopackage.py
Labels: enhancement

#2892 allow disabling pybind11 tests
  easybuild/easyblocks/p/pybind11.py
Labels: enhancement

#2893 call parent post_install_step in EasyBuildMeta easyblock (so postinstallcmds are taken into account)
  easybuild/easyblocks/e/easybuildmeta.py
Labels: enhancement

#2895 update and enhance Maple easyblock for recent versions
  easybuild/easyblocks/m/maple.py
Labels: update

#2862 update scipy easyblock for scipy >= 1.9.0 to use meson/ninja
  easybuild/easyblocks/s/scipy.py
Labels: update

#2896 relax glob pattern to find Mathematica install script
  easybuild/easyblocks/m/mathematica.py
Labels: bug fix, update

#2897 fix linking numexpr with Intel MKL's VML library for imkl >= 2021.x
  easybuild/easyblocks/n/numexpr.py
Labels: bug fix

#2898 Implement CUDA support in the ELPA EasyBlock & fix CPP configure issue on newer ELPA versions
  easybuild/easyblocks/e/elpa.py
Labels: bug fix
