Repository easybuilders/easybuild-easyblocks, pull requests merged in 2023-11, with the labels that each got.

#3030 sync with main + bump version to 4.9.0dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#3004 Install only SuiteSparse libraries with `make install`
  easybuild/easyblocks/s/suitesparse.py
Labels: change

#3009 add new easyblock for HPCC and adapt HPL easyblock
  easybuild/easyblocks/h/hpcc.py
  easybuild/easyblocks/h/hpl.py
Labels: new, change

#3037 update custom intel-compilers easyblock for versions >= 2024
  easybuild/easyblocks/generic/intelbase.py
  easybuild/easyblocks/i/intel_compilers.py
Labels: enhancement

#3038 disable LLVM build downloads from CI in Rust
  easybuild/easyblocks/r/rust.py
Labels: bug fix

#3041 update numpy easyblock for v1.26+
  easybuild/easyblocks/n/numpy.py
Labels: update

#3033 update error detection for PyTorch tests
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix
