Repository easybuilders/easybuild-easyblocks, pull requests merged in 2023-07, with the labels that each got.

#2793 drop unnecessary CUDA stub libraries from $LIBRARY_PATH
  easybuild/easyblocks/c/cuda.py
Labels: enhancement, change

#2957 prepare release notes for EasyBuild v4.8.0 + bump version to 4.8.0
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update, documentation

#2959 release EasyBuild v4.8.0
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/c/cmake.py
  easybuild/easyblocks/generic/binary.py
  easybuild/easyblocks/generic/cargo.py
  easybuild/easyblocks/generic/perlbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/o/openblas.py
  easybuild/easyblocks/r/rust.py
  easybuild/easyblocks/t/torchvision.py
Labels: update

#2960 sync with main + bump version to 4.8.1dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2962 use checkMCR.sh to determine if we have the correct MCR for FreeSurfer
  easybuild/easyblocks/f/freesurfer.py
Labels: enhancement

#2935 Improve depot management in JuliaPackage
  easybuild/easyblocks/generic/juliabundle.py
  easybuild/easyblocks/generic/juliapackage.py
Labels: bug fix

#2967 add support for libvori to CP2K
  easybuild/easyblocks/c/cp2k.py
Labels: enhancement

#2956 disable disk space check in STAR-CCM+ installer
  easybuild/easyblocks/s/star_ccm.py
Labels: bug fix

#2969 Fix type check in cargo EasyBlock
  easybuild/easyblocks/generic/cargo.py
Labels: bug fix
