Repository easybuilders/easybuild-easyblocks, pull requests merged in 2023-10, with the labels that each got.

#3012 only use `-DCMAKE_SKIP_RPATH=ON` for CMake < 3.5.0
  easybuild/easyblocks/generic/cmakemake.py
Labels: bug fix, EESSI

#3014 fix test suite: stop testing with Python 3.5 and Lmod 6.x, stop using `toolchain.DUMMY`
  .github/workflows/unit_tests.yml
  easybuild/easyblocks/h/healpix.py
Labels: bug fix, EasyBuild-5.0

#3013 update version of `config.guess` used by `ConfigureMake`
  easybuild/easyblocks/generic/configuremake.py
Labels: update, EasyBuild-5.0

#3005 remove stray newline in error message produced by PyTorch easyblock
  easybuild/easyblocks/p/pytorch.py
Labels: bug fix

#3016 use more test programs in sanity check step of OpenMPI easyblock
  easybuild/easyblocks/o/openmpi.py
Labels: enhancement

#3015 stop importing from easybuild.tools.py2vs3 (+ minor cleanup in init easyblocks test)
  easybuild/easyblocks/generic/configuremake.py
  easybuild/easyblocks/generic/makecp.py
  test/easyblocks/init_easyblocks.py
Labels: bug fix, EasyBuild-5.0

#3019 don't auto-enable use of `-DSCOTCH_PTHREAD` when using MPI library other than Intel MPI in SCOTCH easyblock
  easybuild/easyblocks/s/scotch.py
Labels: change, EasyBuild-5.0

#3021 fix CMAKE_PREFIX_PATH in mkl easyblock
  easybuild/easyblocks/i/imkl.py
Labels: enhancement

#3010 don't blindly overwrite `-Dccflags` + honour `preconfigopts` in Perl easyblock
  easybuild/easyblocks/p/perl.py
Labels: enhancement

#3011 enhance TensorFlow easyblock to avoid use of `-mcpu=native` for XNNPACK component when building on aarch64
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix, EESSI

#3024 Fix the blas/lapack name passed to meson when building recent scipy versions (>= 1.9.0) on top of Intel MKL
  easybuild/easyblocks/s/scipy.py
Labels: bug fix

#3023 update sanity check in wxPython easyblock for version 4.2.0
  easybuild/easyblocks/w/wxpython.py
Labels: update

#2997 update WRF easyblock to correctly determine `WRF*` subdirectory for WRF versions >= 4.5.1
  easybuild/easyblocks/w/wrf.py
Labels: update

#3007 fix `--sanity-check-only` and `--module-only` for UCX plugins
  easybuild/easyblocks/u/ucx_plugins.py
Labels: bug fix

#3027 prepare release notes for EasyBuild v4.8.2 + bump version to 4.8.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#3029 release EasyBuild v4.8.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/conda.py
  easybuild/easyblocks/generic/configuremake.py
  easybuild/easyblocks/generic/perlbundle.py
  easybuild/easyblocks/i/imkl.py
  easybuild/easyblocks/n/numpy.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/p/perl.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/s/scipy.py
  easybuild/easyblocks/t/tbb.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/u/ucx_plugins.py
  easybuild/easyblocks/w/wrf.py
  easybuild/easyblocks/w/wxpython.py
Labels: update

#3028 Allow version mismatch and include versionsuffix in `ModuleRC` easyblock
  easybuild/easyblocks/generic/modulerc.py
Labels: enhancement, bug fix

#3020 new easyblock for PALM
  easybuild/easyblocks/p/palm.py
Labels: new
