Repository easybuilders/easybuild-easyblocks, pull requests merged in 2023-09, with the labels that each got.

#2928 update Score-P easyblock to use --with-nocross-compiler-suite=nvhpc for recent software versions + unset `$CPPFLAGS`, `$LDFLAGS`, `$LIB` which may interfere with configure magic
  easybuild/easyblocks/s/score_p.py
Labels: enhancement

#2218 correctly determine path to active binutils in TensorFlow easyblock
  easybuild/easyblocks/t/tensorflow.py
Labels: bug fix, EESSI

#2993 inherit `build_*` and `install_*` custom easyconfig parameters from `MesonNinja` in `CMakeNinja` easyblock
  easybuild/easyblocks/generic/cmakeninja.py
Labels: bug fix

#2557 patch Java binaries/libraries when using alternate sysroot to ensure correct glibc & co are picked up + add custom sanity check
  easybuild/easyblocks/j/java.py
Labels: enhancement, bug fix, EESSI

#2985 enhance Mesa easyblock to append EGL vendor library directory path to `$__EGL_VENDOR_LIBRARY_DIRS`
  easybuild/easyblocks/m/mesa.py
Labels: enhancement, bug fix

#2994 rename LLVM dependency subdirectories instead of symlinking them
  easybuild/easyblocks/l/llvm.py
Labels: enhancement, change

#2995 resolve symlinks in paths used for patchelf in Java easyblock, and make sure they are unique
  easybuild/easyblocks/j/java.py
Labels: bug fix

#2942 handle new directory structure for Intel Advisor
  easybuild/easyblocks/a/advisor.py
Labels: update

#2998 prepare release notes for EasyBuild v4.8.1 + bump version to 4.8.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update, documentation

#3001 minor fixes in v4.8.1 release notes
  RELEASE_NOTES
Labels: bug fix, documentation

#3000 release EasyBuild v4.8.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/advisor.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/c/cp2k.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/f/freesurfer.py
  easybuild/easyblocks/generic/cargo.py
  easybuild/easyblocks/generic/cmakeninja.py
  easybuild/easyblocks/generic/juliabundle.py
  easybuild/easyblocks/generic/juliapackage.py
  easybuild/easyblocks/generic/mesonninja.py
  easybuild/easyblocks/generic/perlmodule.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/i/imkl.py
  easybuild/easyblocks/j/java.py
  easybuild/easyblocks/l/llvm.py
  easybuild/easyblocks/m/matlab.py
  easybuild/easyblocks/m/mesa.py
  easybuild/easyblocks/m/mxnet.py
  easybuild/easyblocks/o/opencv.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/p/petsc.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/s/scipy.py
  easybuild/easyblocks/s/score_p.py
  easybuild/easyblocks/s/star_ccm.py
  easybuild/easyblocks/s/sympy.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/tensorflow_compression.py
  test/easyblocks/easyblock_specific.py
Labels: update

#3002 sync with main + bump version to 4.8.2dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#2837 allow use of `test_cmd` without `runtest` for `ConfigureMake`
  easybuild/easyblocks/generic/configuremake.py
Labels: enhancement

#2838 enhance `CMakeMake` easyblock to run `ctest` command if `runtest` is `True`
  easybuild/easyblocks/generic/cmakemake.py
Labels: enhancement

#2927 fix creation of symlink for libraries in TBB easyblock
  easybuild/easyblocks/t/tbb.py
Labels: bug fix

#2999 update numpy easyblock to be able to use FlexiBLAS with MKL as dependency
  easybuild/easyblocks/n/numpy.py
Labels: enhancement

#3003 add error regexp for PyTorch tests run in subprocess and enhance error message
  easybuild/easyblocks/p/pytorch.py
Labels: enhancement
