Repository easybuilders/easybuild-easyblocks, pull requests merged in 2024-09, with the labels that each got.

#3391 update custom easyblock for PETSc to consider `include/suitesparse` subdirectory for SuiteSparse headers
  easybuild/easyblocks/p/petsc.py
Labels: enhancement

#3430 make sure to raise an error if `pick_python_cmd` returns False for Python bundles/packages
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#3435 make sure user packages are not used in sanity check of PythonBundle
  easybuild/easyblocks/generic/pythonbundle.py
Labels: enhancement

#3396 enhance custom easyblock for GCC to use `with-arch` option for nvptx with 13.1+
  easybuild/easyblocks/g/gcc.py
Labels: enhancement

#3438 enhance binutils easyblock to explicitely pass msgpack configure option
  easybuild/easyblocks/b/binutils.py
Labels: enhancement

#3439 fix sanity check for Geant4 >= v11.2
  easybuild/easyblocks/g/geant4.py
Labels: update

#3434 update sanity check in OpenFOAM easyblock, since there's no `modifyMesh` in OpenFOAM 12
  easybuild/easyblocks/o/openfoam.py
Labels: update

#3443 don't wipe build environment before building opam in install step of OCaml easyblock
  easybuild/easyblocks/o/ocaml.py
Labels: bug fix

#3444 fix typo in docstring for JuliaBundle & JuliaPackage
  easybuild/easyblocks/generic/juliabundle.py
  easybuild/easyblocks/generic/juliapackage.py
Labels: bug fix

#3445 release EasyBuild v4.9.3
  .github/workflows/linting.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/ansys.py
  easybuild/easyblocks/b/bazel.py
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/b/boost.py
  easybuild/easyblocks/e/easybuildmeta.py
  easybuild/easyblocks/e/esmf.py
  easybuild/easyblocks/e/extrae.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/g/geant4.py
  easybuild/easyblocks/generic/cargo.py
  easybuild/easyblocks/generic/cargopythonpackage.py
  easybuild/easyblocks/generic/juliabundle.py
  easybuild/easyblocks/generic/juliapackage.py
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/generic/rpackage.py
  easybuild/easyblocks/generic/rubygem.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/m/mcr.py
  easybuild/easyblocks/m/mpich.py
  easybuild/easyblocks/o/ocaml.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/o/openssl_wrapper.py
  easybuild/easyblocks/o/orca.py
  easybuild/easyblocks/p/palm.py
  easybuild/easyblocks/p/petsc.py
  easybuild/easyblocks/p/psmpi.py
  easybuild/easyblocks/p/python.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/q/quantumespresso.py
  easybuild/easyblocks/q/quantumespressocmake.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/tkinter.py
  easybuild/easyblocks/w/wps.py
Labels: update

#3446 sync with main + bump version to 4.9.4dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#3448 copy `EasyConfig` instance in constructor of `Bundle` and `Cargo` easyblocks before changes to it
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cargo.py
Labels: bug fix

#3447 sync with develop (20240915)
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/g/geant4.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cargo.py
  easybuild/easyblocks/generic/cargopythonpackage.py
  easybuild/easyblocks/generic/juliabundle.py
  easybuild/easyblocks/generic/juliapackage.py
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/generic/rpackage.py
  easybuild/easyblocks/i/impi.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/o/ocaml.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/orca.py
  easybuild/easyblocks/p/palm.py
  easybuild/easyblocks/p/petsc.py
  easybuild/easyblocks/p/psmpi.py
  easybuild/easyblocks/q/quantumespresso.py
Labels: update, EasyBuild-5.0

#3431 allow Python bundles and packages to specify a maximum Python version for the system toolchain
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  test/easyblocks/module.py
Labels: enhancement

#3283 Ignore Python from virtualenvs in GROMACS configure via `-DPython3_FIND_VIRTUALENV=STANDARD`
  easybuild/easyblocks/g/gromacs.py
Labels: bug fix

#3451 enhance custom easyblock for NCCL: add licence to NCCL installation
  easybuild/easyblocks/n/nccl.py
Labels: enhancement

#3455 prepare release notes for EasyBuild v4.9.4 + bump version to 4.9.4
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#3456 release EasyBuild v4.9.4
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cargo.py
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/n/nccl.py
  test/easyblocks/module.py
Labels: update

#3457 sync with main + bump version to 4.9.5dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#3459 sync with develop (20240923)
  RELEASE_NOTES
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/g/gromacs.py
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/n/nccl.py
  test/easyblocks/module.py
Labels: update, EasyBuild-5.0

#3462 Adding RISCV support to build Qt5
  easybuild/easyblocks/q/qt.py
Labels: enhancement

#3458 Enhance AOCC EasyBlock to work with LLVM 16 and newer
  easybuild/easyblocks/a/aocc.py
Labels: update

#3464 strip leading `local/` from pylibdir where appropriate
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#3452 Make `CMakeMake` respect the toolchainopts when selecting build type
  easybuild/easyblocks/generic/cmakemake.py
Labels: bug fix, EasyBuild-5.0
