Repository easybuilders/easybuild-easyblocks, pull requests merged in 2024-11, with the labels that each got.

#3494 Enhance NAMD easyblock to support NAMD v3.0
  easybuild/easyblocks/n/namd.py
Labels: update

#3500 sync with develop (2024-11-06)
  easybuild/easyblocks/generic/cargo.py
  easybuild/easyblocks/i/intel_compilers.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/n/namd.py
  easybuild/easyblocks/o/openblas.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/s/score_p.py
  easybuild/easyblocks/s/suitesparse.py
Labels: EasyBuild-5.0

#3483 enhance cargo easyblock for sources from git repositories
  easybuild/easyblocks/generic/cargo.py
Labels: enhancement

#3472 Enhance generic `Bundle` easyblock to transfer module requirements of components
  easybuild/easyblocks/generic/bundle.py
Labels: enhancement

#3502 sync with develop (2024-11-10)
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cargo.py
Labels: EasyBuild-5.0

#3504 revert changes from PR #3472, seems to be leading to an infinite loop in easyconfigs test suite?
  easybuild/easyblocks/generic/bundle.py
Labels: bug fix

#3506 sync with develop (2024-11-13)
  easybuild/easyblocks/generic/bundle.py
Labels: EasyBuild-5.0

#3501 gromacs: make it possible to disable single precision as build target.
  easybuild/easyblocks/g/gromacs.py
Labels: enhancement

#3519 force use of `bash` for `Allwmake` scripts in OpenFOAM easyblock
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix
