Repository easybuilders/easybuild-easyblocks, pull requests merged in 2024-06, with the labels that each got.

#3347 Allow external PRRTE in openmpi easyblock
  easybuild/easyblocks/o/openmpi.py
Labels: enhancement

#3349 sync with develop (20240605)
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/o/openssl_wrapper.py
Labels: EasyBuild-5.0

#3341 avoid sanity check on the software itself for CargoPythonBundle easyblock
  easybuild/easyblocks/generic/cargopythonbundle.py
Labels: bug fix

#3329 Always override the compiler version check for CUDA installations
  easybuild/easyblocks/c/cuda.py
Labels: enhancement

#3313 don't manipulate setup.py for Python 3.12+ when using alternate sysroot
  easybuild/easyblocks/p/python.py
Labels: bug fix

#3322 add libjpeg-turbo to include dir for torchvision easyblock
  easybuild/easyblocks/t/torchvision.py
Labels: enhancement

#3346 fix malformed `$CPATH` for intel-compilers on Debian/Ubuntu
  easybuild/easyblocks/i/intel_compilers.py
Labels: priority:critical, bug fix

#3328 Add a sanity check for OpenFOAM's `wmake` to make sure it finds the compiler commands
  easybuild/easyblocks/o/openfoam.py
Labels: enhancement

#3353 always specify custom value for `sanity_check_paths` in custom easyblock for torchvision
  easybuild/easyblocks/t/torchvision.py
Labels: bug fix

#3356 prepare release notes for EasyBuild v4.9.2 + bump version to 4.9.2
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update, documentation

#3357 release EasyBuild v4.9.2
  .github/workflows/unit_tests.yml
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/abaqus.py
  easybuild/easyblocks/a/aedt.py
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/f/fftw.py
  easybuild/easyblocks/g/gamess_us.py
  easybuild/easyblocks/generic/cargopythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/i/intel_compilers.py
  easybuild/easyblocks/j/java.py
  easybuild/easyblocks/m/mesa.py
  easybuild/easyblocks/m/metalwalls.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/o/openssl_wrapper.py
  easybuild/easyblocks/o/optislang.py
  easybuild/easyblocks/p/python.py
  easybuild/easyblocks/q/quantumespresso.py
  easybuild/easyblocks/q/quantumespressocmake.py
  easybuild/easyblocks/s/stata.py
  easybuild/easyblocks/t/torchvision.py
  easybuild/easyblocks/u/ucx_plugins.py
Labels: update

#3358 also consider 'normalised' package name with underscore rather than dash in EasyBuild easyblock
  easybuild/easyblocks/e/easybuildmeta.py
Labels: bug fix

#3359 sync with main + bump version to 4.9.3dev
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
Labels: update

#3360 support PRRTE MCA environment variable for oversubscription in OpenMPI easyblock
  easybuild/easyblocks/o/openmpi.py
Labels: bug fix

#3365 use `flake8` 7.0.0 for linting easyblocks
  .github/workflows/linting.yml
Labels: bug fix

#3364 fix import of `parse` in `openssl_wrapper.py` for Python 2.7
  easybuild/easyblocks/o/openssl_wrapper.py
Labels: bug fix

#3366 make sure that OpenFOAM's wmake can find MPFR and GMP if CGAL >= 5.0 (header-only) is used
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix, EESSI

#3367 sync with develop (20240619)
  RELEASE_NOTES
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/e/easybuildmeta.py
  easybuild/easyblocks/generic/cargopythonbundle.py
  easybuild/easyblocks/i/intel_compilers.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/o/openssl_wrapper.py
  easybuild/easyblocks/p/python.py
  easybuild/easyblocks/t/torchvision.py
Labels: update, EasyBuild-5.0

#3369 support >= 2024a `for MCR`
  easybuild/easyblocks/m/mcr.py
Labels: bug fix
