Repository easybuilders/easybuild-easyblocks, pull requests merged in 2024-03, with the labels that each got.

#3238 sync with develop (20240227)
  easybuild/easyblocks/c/clang_aomp.py
  easybuild/easyblocks/g/gurobi.py
  easybuild/easyblocks/generic/cargo.py
  easybuild/easyblocks/generic/perlmodule.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/o/openmpi.py
  easybuild/easyblocks/p/pytorch.py
Labels: EasyBuild-5.0

#3242 update RPackage to make sure that asynchronous installation command is run in correct working directory
  easybuild/easyblocks/generic/rpackage.py
Labels: bug fix, EasyBuild-5.0

#3206 replace `run_cmd` with `run_shell_cmd` in custom easyblock for MXNet (`mxnet.py`)
  easybuild/easyblocks/m/mxnet.py
Labels: change, EasyBuild-5.0

#3204 replace `run_cmd` with `run_shell_cmd` in custom easyblock for NAMD (`namd.py`)
  easybuild/easyblocks/n/namd.py
Labels: change, EasyBuild-5.0

#3235 fix OCaml easyblock for recent versions
  easybuild/easyblocks/o/ocaml.py
Labels: enhancement

#3243 replace `run_cmd` with `run_shell_cmd` in custom easyblock for OCaml (`ocaml.py`)
  easybuild/easyblocks/o/ocaml.py
Labels: change, EasyBuild-5.0

#3236 only run torchvision w/cuda sanity check command test if GPU is present
  easybuild/easyblocks/t/torchvision.py
Labels: bug fix

#3245 replace `log.warn` with `log.warning`
  easybuild/easyblocks/c/clang.py
  easybuild/easyblocks/c/clang_aomp.py
  easybuild/easyblocks/generic/gopackage.py
  easybuild/easyblocks/p/pyquante.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/v/vmd.py
Labels: enhancement, EasyBuild-5.0

#3244 replace `run_cmd` with `run_shell_cmd` in custom easyblock for LAMMPS (`lammps.py`)
  easybuild/easyblocks/l/lammps.py
Labels: change, EasyBuild-5.0

#2922 use proxy in sanity check of `EB_OpenSSL_wrapper`
  easybuild/easyblocks/o/openssl_wrapper.py
Labels: enhancement

#3064 rename `run` method to `install_extension`, and likewise for `prerun` to `pre_install_extension`, `postrun` to `post_install_extension`, and `run_async` to `install_extension_async`
  easybuild/easyblocks/generic/juliapackage.py
  easybuild/easyblocks/generic/ocamlpackage.py
  easybuild/easyblocks/generic/octavepackage.py
  easybuild/easyblocks/generic/perlmodule.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/generic/rpackage.py
  easybuild/easyblocks/generic/rubygem.py
  easybuild/easyblocks/generic/tarball.py
  easybuild/easyblocks/m/mxnet.py
  easybuild/easyblocks/n/numpy.py
  easybuild/easyblocks/p/pbdmpi.py
  easybuild/easyblocks/r/reticulate.py
  easybuild/easyblocks/r/rmpi.py
  easybuild/easyblocks/r/rserve.py
  easybuild/easyblocks/s/scipion.py
Labels: change, EasyBuild-5.0

#3251 sync with develop (20240311)
  easybuild/easyblocks/l/libint.py
  easybuild/easyblocks/o/openssl_wrapper.py
  easybuild/easyblocks/t/torchvision.py
Labels: EasyBuild-5.0

#3229 remove trailing slash in `SLEPC_DIR` in configure step of custom easyblock for SLEPc
  easybuild/easyblocks/s/slepc.py
Labels: bug fix

#3256 set `$LIBRARY_PATH` and disable building of NVPTX offload support on RISC-V systems
  easybuild/easyblocks/g/gcc.py
Labels: enhancement

#3254 do not rename GCC's include-fixed directory by default + add script to regenerate it
  easybuild/easyblocks/g/gcc.py
  test/easyblocks/init_easyblocks.py
Labels: enhancement, bug fix, change

#3241 Feature improve QuantumESPRESSO easyblock
  easybuild/easyblocks/q/quantumespresso.py
Labels: bug fix

#3250 allow overriding `testinstall` in PyTorch easyconfigs
  easybuild/easyblocks/p/pytorch.py
Labels: enhancement

#3258 Removed FoX constraint on GIPAW for QuantumESPRESSO easyblock
  easybuild/easyblocks/q/quantumespresso.py
Labels: bug fix

#3232 fix OpenFOAM easyblock to fix `motorBike` example in sanity check for v >=11
  easybuild/easyblocks/o/openfoam.py
Labels: bug fix

#3261 sync with develop (20240328)
  easybuild/easyblocks/g/gcc.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/q/quantumespresso.py
  easybuild/easyblocks/s/slepc.py
  test/easyblocks/init_easyblocks.py
Labels: EasyBuild-5.0

#3260 Add support for conda provided by miniforge
  easybuild/easyblocks/generic/conda.py
Labels: enhancement

#3262 Move Go build junk into builddir
  easybuild/easyblocks/generic/gopackage.py
Labels: enhancement
