Repository easybuilders/easybuild-easyblocks, pull requests merged in 2025-07, with the labels that each got.

#3808 fix `--module-only` builds for `Term::ReadLine::Gnu`
  easybuild/easyblocks/t/termreadlinegnu.py
Labels: bug fix

#3813 simplify use of `self.cfg.dependencies()` in `PETSc`
  easybuild/easyblocks/p/petsc.py
Labels: code cleanup

#3775 Reset `runtest` for components in a bundle
  easybuild/easyblocks/generic/bundle.py
Labels: bug fix

#3821 Add support for `hwloc` to `MPICH` easyblock
  easybuild/easyblocks/m/mpich.py
Labels: enhancement, bug fix

#3819 Fix condition to ignore failed LLVM GPU tests
  easybuild/easyblocks/l/llvm.py
Labels: bug fix

#3815 Refactor LLVM easyblock and install OpenMP library symlinks
  easybuild/easyblocks/l/llvm.py
Labels: enhancement, code cleanup

#3822 move `libiberty.a` binutils library to `lib` subdirectory if it's the only file in `lib64` subdirectory
  easybuild/easyblocks/b/binutils.py
Labels: bug fix, change

#3781 Moved logic from the constructor to `configure_step` in LLVM easyblock (so it can be used to install bundle component)
  easybuild/easyblocks/l/llvm.py
Labels: bug fix, EESSI

#3780 Simplify remaining super() calls
  easybuild/easyblocks/generic/buildenv.py
  easybuild/easyblocks/o/openblas.py
Labels: code cleanup

#3761 remove `2to3` file from sanity check in Anaconda easyblock (no longer there in recent versions)
  easybuild/easyblocks/a/anaconda.py
Labels: update

#3477 fix `enhance_sanity_check` for `PythonPackage`
  easybuild/easyblocks/generic/pythonpackage.py
Labels: bug fix

#3768 update Rust easyblock to disable installations of docs via `--disable-docs` configure option
  easybuild/easyblocks/r/rust.py
Labels: change

#3829 release EasyBuild v5.1.1
  RELEASE_NOTES
  easybuild/easyblocks/__init__.py
  easybuild/easyblocks/a/abaqus.py
  easybuild/easyblocks/a/anaconda.py
  easybuild/easyblocks/b/binutils.py
  easybuild/easyblocks/b/blis.py
  easybuild/easyblocks/c/cmake.py
  easybuild/easyblocks/c/cuda.py
  easybuild/easyblocks/generic/binary.py
  easybuild/easyblocks/generic/buildenv.py
  easybuild/easyblocks/generic/bundle.py
  easybuild/easyblocks/generic/cargo.py
  easybuild/easyblocks/generic/cmakemake.py
  easybuild/easyblocks/generic/cmakeninja.py
  easybuild/easyblocks/generic/conda.py
  easybuild/easyblocks/generic/pythonbundle.py
  easybuild/easyblocks/generic/pythonpackage.py
  easybuild/easyblocks/l/lammps.py
  easybuild/easyblocks/l/llvm.py
  easybuild/easyblocks/m/mesa.py
  easybuild/easyblocks/m/metalwalls.py
  easybuild/easyblocks/m/mpich.py
  easybuild/easyblocks/n/numpy.py
  easybuild/easyblocks/o/openblas.py
  easybuild/easyblocks/o/openfoam.py
  easybuild/easyblocks/o/orca.py
  easybuild/easyblocks/p/petsc.py
  easybuild/easyblocks/p/python.py
  easybuild/easyblocks/p/pytorch.py
  easybuild/easyblocks/r/rust.py
  easybuild/easyblocks/s/scipy.py
  easybuild/easyblocks/s/slepc.py
  easybuild/easyblocks/s/superlu.py
  easybuild/easyblocks/t/tensorflow.py
  easybuild/easyblocks/t/termreadlinegnu.py
  test/easyblocks/easyblock_specific.py
  test/easyblocks/general.py
  test/easyblocks/init_easyblocks.py
  test/easyblocks/module.py
  test/easyblocks/suite.py
Labels: update

#3832 disable UCX signal catching in Java
  easybuild/easyblocks/j/java.py
Labels: bug fix

#3793 use property for gcc_prefix/gcc_root in LLVM easyblock
  easybuild/easyblocks/l/llvm.py
Labels: bug fix

#3836 remove default `separate_build_dir = True` in `aramdillo.py`
  easybuild/easyblocks/a/armadillo.py
Labels: code cleanup

#3838 remove default `separate_build_dir = True` in `elsi.py`
  easybuild/easyblocks/e/elsi.py
Labels: code cleanup

#3841 cleanup ancient version support in `root.py`
  easybuild/easyblocks/r/root.py
Labels: change, code cleanup

#3844 remove default `separate_build_dir = True` in `openbabel.py`
  easybuild/easyblocks/o/openbabel.py
Labels: code cleanup

#3840 remove default `separate_build_dir = True` in `superlu.py`
  easybuild/easyblocks/s/superlu.py
Labels: code cleanup

#3850 Update DualSPHysics sanity checks for newer version
  easybuild/easyblocks/d/dualsphysics.py
Labels: bug fix

#3851 LLVM: Fix missing `LIBOMPTARGET_DEVICE_ARCHITECTURES` in third stage of bootstrap build
  easybuild/easyblocks/l/llvm.py
Labels: bug fix

#3765 Update tensorflow easyblock for CUDA support in TensorFlow 2.18+
  easybuild/easyblocks/t/tensorflow.py
Labels: update

#3857 add back configure options for PETSc dependencies with generic `--with` options
  easybuild/easyblocks/p/petsc.py
Labels: bug fix
